README.md
I also added a new category "text processing" with three entries because
they didn't really seem to fit any where else.
=> Add xsv, byte swapping, cbor, suffix arrays, regexes and elastic tabstops

README.md
=> Add clog to applications

README.md
`clap` has changed quite a bit from it's simple beginnings ;)
=> updates clap description

README.md
Especially helpful for beginners.
=> Added rust-clippy

README.md
Propose itertools and typemap.
Disclosure: I maintain itertools.
=> Add itertools, typemap

README.md
=> Added handlebars-rust and handlebars-iron

README.md
no travis build integration yet, but working on both nightly and beta rust
=> adding cassandra to the database section.

README.md
=> Add chyh1990/imageproc

README.md
Date structures to 
Data structures
=> fix a minor typo

README.md
Hi,
serde-rs is pretty popular framework for serialization of data structures.
Am not sure wether I've added it to the right category - but this seems to be the best fit.
regards,
felix
=> list serde-rs, a framework to generically serialize Rust data structures

README.md
added rust-peg to the parser section, because it truely is awesome
=> add rust-peg

README.md
=> Added ORM listing

README.md
Add Coio-rs into a new section "Asynchronous".
=> Add Coio-rs

README.md
Added a section for astronomy and astro-rust under it.
=> Added astro-rust

README.md
Namely crossbeam, rayon, generic-array, roaring-rs and chomp.
=> Added some awesome libraries

README.md
Add generic-dns-update, a tool to update DNS zonefiles with your ip address
=> Add generic-dns-update

README.md
Hi!
As the ears crate is unmaintained I forked it and fixed some stuff. Also added Windows ci and uploaded it to crates.io.
=> Change ears repository

README.md
Add the etcd crate to the database section.
=> Add etcd crate.

README.md
[Tokei](https://github.com/Aaronepower/tokei), is a program some people might want, maybe?
=> Added Tokei

hello.rs
See https://github.com/zhaopuming/awesome-d/commits/master/hello.d
=> Add a Rust file so GitHub recognizes the language

README.md
Separated section for embedded systems created.
Rust-cross added and raspberry pi moved to this section.
=> Add cross compilation for Rust

README.md
- Vagga is a containerization tool written in rust
=> Add vagga to list

README.md
Tikv : distributed KV database powered by Rust
=> add Tikv : distributed KV database powered by Rust

README.md
[Sciter](http://sciter.com) is an embeddable multiplatform HTML/CSS/script engine with GPU accelerated rendering designed to render modern desktop application UI. It's a compact, single dll/dylib/so file (4-8 mb), engine without any additional dependencies.
Sciter has bindings for C++, Delphi, D, Go, .NET, Python and Rust languages.
This one allows you easily create the multiplatform desktop GUI with HTML/CSS and writing application logic in Rust.
Who agrees that this change should be merged could add your reactions (e.g. :+1:) to this pull request.
=> Added sciter-rust gui library

README.md
A while back I wrote an application for managing systemd services on Linux systems with Rust and GTK-rs for the GUI front-end.
=> Add systemd-manager

README.md
A new application that I've written which features an optional GTK3 user interface and TVDB support for adding titles to episodes.
=> Add tv-renamer

README.md
=> Add autumnai/collenchyma

README.md
=> Add Lua bindings

README.md
I am not sure which section more suitable — FFI (because it is bindings) or Virtualization (because its a CPU emulator bindings).
=> Add unicorn-rs: Rust bindings for the unicorn CPU emulator

README.md
Rust's std::collections extensions and new useful libraries like trie, lists, lru-cache and so on.
=> Add github/contain-rs collection

README.md
=> nominating rusty-machine

README.md
Closes https://github.com/gfx-rs/gfx/issues/946
=> Added Graphics section, gfx-rs and specs projects

README.md
...and populate with temporary file management libraries.
=> Add a filesystem category

README.md
Add Dropbox's Brotli decompressor 😄
=> Add rust-brotli

README.md
https://github.com/vityafx/urlshortener-rs
https://github.com/vityafx/challonge-rs
=> Added 2 libraries about url shortening and game development.

README.md
Add https://github.com/dpc/mioco
=> Add dpc/mioco

README.md
This plugin has custom icons for Rust files.
=> Add AfterglowIntelliJ

README.md
IntelliJ Platform plugin with basic Toml support
=> Add intellij-toml

README.md
I wrote this Rust application in May 2015 to learn Rust and practice my GA skills. It could easily be rewritten as a library (the GA part is already), and I believe would be useful as example code. While developing, I worked closely with the Rust IRC community to produce correct, idiomatic code.
=> Add andschwa/rust-genetic-algorithm

README.md
Add a library for parsing email
=> Add staktrace/mailparse

README.md
This pull request should fix issue #197. Please let me know if there is anything else in this section you would like fixed.
=> Correct game development section

README.md
added White-Oak/qml-rust a newer implementation of QML bindings
=> added White-Oak/qml-rust

README.md
Because it is deprecated in favor of futures-rs
=> Remove tangle

README.md
utility to compare Rust micro-benchmarks
=> add BurntSushi/cargo-benchcmp

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kud1ing/awesome-rust/212)
=> Added build status image

README.md
=> add rust-lang-nursery/log, slog-rs/slog, sfackler/log4rs

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kud1ing/awesome-rust/215)
=> Add lib facebook accountkit

README.md
This is the best tutorial I've come across on really understanding Rust's borrow checker.
=> Add "Learning Rust With Entirely Too Many Linked Lists"

README.md
These are the rust-related plugins I am currently using for development.
=> Adding rust vim plugins to IDE section

README.md
а cross-platform, GPU enhanced terminal emulator
=> Add alacritty

README.md
Wasn't sure where to put it, since it doesn't really fit in under the categories. Made a new category "Window Managers" since I could foresee others going here as well.
Please tell me if there is a better place to put it.
=> Added Way Cooler to README

README.md
Config is a layered configuration system for Rust applications (with strong support for 12-factor applications).
https://github.com/mehcode/config-rs
=> Add config-rs

README.md
**fs_extra** - expanding opportunities standard library std::fs and std::io.
**Key features:**
- Copy files with recept information about process.
- Copy directory recursively and recept information about process.
- Copy list directoies and files recursively and recept information about process.
- Move files with recept information about process.
- Move directories recursively and recept information about process.
- Move list directoies and files recursively and recept information about process.
- One method for create and write String content in file.
- One method for open and read String content from file.
- Get size folder
=> add fs_extra

README.md
https://github.com/kud1ing/awesome-rust/issues/258
=> Add bindings to Nuklear

README.md
also: there was some whitespace after nuklear and my editor didn't like it :(
=> update rst -> artifact

README.md
Added Rustual Boy to Emulator section
=> Added Virtual Boy Emulator

README.md
Added Emulator development section for ROM hacking tools, etc and added one for the SNES.
=> Added new section in Emulators

README.md
added dyon link
added gluon link
added ketos link
=> added scripting section

README.md
Not sure if this is the right place as there are no Password Managers section.
=> Add mpw-rs to Cryptography

README.md
This also adds the deployment section :)
=> Add mini-docker-rust

README.md
Polish is a mini testing framework for the Rust system programming language meant to allow the writing of test-driven applications in a unified and expressive manner.
=> added Polish

README.md
Let me know if I missed anything!
=> Add Emacs information to IDE section

README.md
=> Add OpenCV

README.md
Add entry for [whatlang-rs](https://github.com/greyblake/whatlang-rs)  - natural language detection library
=> Add whatlang-rs entry

README.md
=> add array_tool crate

README.md
=> Add University of Pennsylvania Comp Sci course

README.md
=> Add habitat

README.md
=> Bring PostgreSQL and Sqlite under SQL bullet point

README.md
Haven't found any criteria to meet to be included in the list, so will try with my small project. I was searching for a scaffolding tool, but found only few ones, which were not so easy to use (in my opinion). So I decided to make my own. It's roughly the same as Yeoman, but simpler. It doesn't have any generators, instead it uses templates (Handlebars) that are filled with user input.
=> Adding quick-skeleton

README.md
Hello
Mockito has been stable for a while now and I've added some nice features along the past year.
Would be great to see it on awesome-rust :)
=> Add Mockito to the Testing group

README.md
Just adding my little password library, it is very well documented and tested; I think it worth a look. Also, I sorted the Cryptography section.
=> Add rust-djangohashers and sort Cryptography

README.md
Weld added.
Parity and parity-bitcoin moved to correct alphabetical ordered position.
=> Weld - Full fake REST API generator 

README.md
Hi, I added a link to the image processing CLI that I wrote, which mainly is a wrapper around the Piston image package, but also has implementation for generating histograms.
Since I'm using it at work, maybe it can be useful for others.
=> Add Image Processing CLI

README.md
Just adding https://github.com/ticki/termion to the list 👍
@ticki
=> Add github.com/ticki/termion

README.md
kylyp: The project use rust, rocket, diesel, postgresql, and responsive design to build a new Forum.
[kylyp](https://github.com/mcux/kylyp)
=> add kylyp project

README.md
Added the rodio audio playback library written in Rust by tomaka
=> Added rodio audio library

README.md
- [Are we _web_ yet? -- http://www.arewewebyet.org](http://www.arewewebyet.org)
=> Add Are we web yet? to Web programming section

README.md
Add a testing tool similar to QuickCheck.
=> Add altsysrq/proptest

README.md
=> add jonathandturner/rhai

README.md
I was not sure if it's okay to add your own project to the list. If not, I will be happy to close this PR :)
=> Add ipnetwork to the list of libraries

README.md
It's an application written in Rust, and it's awesome.
=> add quadrupleslap/leven

README.md
Hi! I'd love to add a library I put together to your awesome list! It's such a great resource! The repo link is in the commit, the crate lives at [https://crates.io/crates/bnf](https://crates.io/crates/bnf)
=> Add BNF parser to curated list

README.md
let's see if I caught everything
=> fix redirects in README

README.md
Add extra games:
* magog
* rust-doom
* rust-quake
rust-doom and rust-quake may be better placed under a new heading? Perhaps "Game Renderer"?
=> Add extra games

README.md
Zbox is a zero-details, privacy-focused embeddable file system. Please add this link, thanks.
=> add link to zbox

README.md
It's a great tool, and it appears a standalone file watcher is still missing here.
=> Add mattgreen/watchexec

README.md
Closes https://github.com/rust-unofficial/awesome-rust/issues/389
=> Added trust

README.md
Add euclider to the _Applications written in Rust_ section.
=> Add euclider

README.md
kylyp also rename muro in new orgnaization.
=> kylyp also rename muro in new orgnaization.

README.md
i think it should have a category for macro
cute and hado are the most useful macro in my work and also very awesome
=> add some awesome-macro

README.md
CLI manager of one-time password generators aka Google Authenticator (TOTP)
=> Add Zebradil/rustotpony

README.md
These are two libraries I've been working on for a fair amount of time within my `artifact` project. Their use cases are both pretty solid IMO and they should be searchable on this excellent list!
Thanks!
=> path_abs and stfu8

README.md
Hi guys. If my project isn't too small, I'd like to add my game manager/launcher written in Rust. Thanks for considering it!
=> Add eidolon to list

README.md
It is blocking all PR as CI is failing for these repositories.
=> Update repos where owner have been changed

README.md
Create a new `Cryptocurrencies` category in `Applications written in Rust` and add `ethaddrgen`.
=> Add `Cryptocurrencies` to `Applications`, add `ethaddrgen`

README.md
The version on cargo is still rough around the edges, but that will change soon, now we have a cargo-based mutation runner.
=> Add llogiq/mutagen to testing

README.md
=> Fix the newrustacean.com link

README.md
https://hackr.io/tutorials/learn-rust
=> Added Community Curated Rust Resources

README.md
=> add a influxdbclient crate

README.md
Retry: sorry, my first PR come from Github interface... i've tried, i've lost. 
I don't find a quick and easy way to update my initial PR.
=> Added Sozu : A HTTP Reverse Proxy

README.md
The badge is linked to Iron's.
=> Fix badge for frank_jwt

README.md
=> Fixed 301 link to wasm-bindgen

README.md
RusticSOM is a library for Self Organising Maps - A type of ANN employing unsupervised learning (clustering).
=> Added RusticSOM under Machine Learning

README.md
=> Add libui most updated repository

README.md
=> Add leaf most updated fork.

README.md
Dear maintainer(s),
I just [got word of this library](https://twitter.com/spacekookie/status/1001139793336717312) and feel it would be an extremely useful addition for the _Library_ » _Command line_ section. Also, [human-centered design](https://en.wikipedia.org/wiki/Human-centered_design) in IT is important (and underappreciated) enough to warrant a new subsection here, which this PR adds as well.
Pinging @yoshuawuyts and @spacekookie, the authors of the library, for visibility (and a chance to consent/dissent).
=> Add yoshuawuyts/human-panic

README.md
Hi! This will add the runiq crate.
I'm not sure if ordering is alphabetical by project or by author?
=> Add runiq binary crate

README.md
=> Add nebulet/nebulet

README.md
This section already existed anyway so let's use it.
=> Move all static site generators to existing static site section

README.md
Monad/MonadIO, Handler, Coroutine/doNotation, Functional Programming features for Rust
=> Add fpRust record

README.md
An experimental next-generation text editor.
=> Add atom/xray

README.md
Eureka is a CLI tool to input and store your ideas without leaving the terminal.
I added the section "Productivity", but if you think the tool belongs in a different section just let me know and I'll change.
=> Add productivity tool eureka

README.md
Hi ! I've been working on a password manager since March 2015. It has little recent commits because it's quite stable and Rust keeps backwards compatibility. Hopefully this project is worthy of being added to "awesome-rust". Feel free to get back with any questions :)
=> adds rooster password manager

README.md
Add crates.io link to be more consistent.
=> Add human-panic crates.io link

README.md
Just a simple and easy-to-use HIBP checker for the command-line.
=> Add checkpwn

README.md
add [ruster](http://forum.ruster.xyz/) : online community in rust for rust community [source](https://github.com/ruster-xyz/ruster)
=> add ruster : online community in rust for rust community 

README.md
For the current Travis build to pass, this needs an update 😄
=> CommonMark HTTPS support

README.md
Both may also be in WebGL and WebAssembly sections in a future re-org
=> Added Kiss3D and Unrust to "game engines"

README.md
Should make Travis happier. :)
=> fix 301 and 404 links

README.md
A new artificial intelligence section has been added with genetic algorithms and machine learning (its previous section has been moved inside this one) repositories.
=> Add genetic algorithms section

README.md
adding a new learning resource - build your own language VM
=> adding a learning resource

README.md
Hi! I'd love if this repo listed the video course that @shepmaster and I are making for Manning Publications. I noted that this is a paid resource, and, full disclosure, the link is an affiliate link. I'm totally cool if you don't want to accept this at all or if you don't want to accept an affiliate link, let me know and I'll edit to remove those params ❤️
=> Add Rust in Motion

README.md
Vulkust game engine is a safe and multithreaded, Vulkan based game engine with focusing on modern features like deferred rendering, cascaded shadow mapping, physical based rendering, ... .
It soon gonna have a stabilized API.
=> vulkust game engine added

README.md
Wanted to add my little HTTP client library as alternative to reqwest 😄
=> Add yukikaze crate

README.md
Try it: http://gitpod.io#https://github.com/BookOwl/snake-rs
=> Added gitpod.io to Rust IDEs

README.md
This PR adds my ddh utility and fixes a bit of alphabetic ordering.
=> Add ddh utility

README.md
=> added cicada unix shell

README.md
=> Add cardano project

README.md
=> plug tinyrick

README.md
This pull request adds new rogue like game.
=> Add new game

README.md
a new Cryptocurrencies solution
=> add Nervos CKB to Cryptocurrencies

README.md
Plume is a blog agregator
Firecracker is an Amazon project for microvms
=> Proposal for addition of Plume and Firecracker

README.md
=> Add NearProtocol to crypto projects

README.md
lsd is a pretty ls based on nerd-fonts.
=> Add github.com/Peltoche/lsd to the System tool section

README.md
A collection of rust github actions
=> Add github actions section

README.md
flutter-rs is a rust project to embed flutter in rust.
=> Add flutter-rs repo

README.md
My framework for creating online games prototype.
=> added victorem

README.md
=> Re: Fix links for CI

README.md
Add a description for `rust-csv`.
=> describe `rust-csv`

README.md
Hey 👋 , how about adding a service category to collect all the available web services for the Rust ecosystem?
=> Add services category

README.md
Added Substrate and Parity-Zcash. Also organized Parity links.
=> Added Cryptocurrency Links

README.md
adding Noria, as seen here: https://www.youtube.com/watch?v=s19G6n0UjsM
=> README: add Noria to database

README.md
Add record for https://github.com/billyevans/tst
=> Add billyevans/tst, Ternary search tree collection

README.md
https://github.com/vishaltelangre/ff
=> Add ff (find-files)

README.md
* fix build status url for s3find
* rename Wilfred/remacs -> remacs/remacs
* fix argangodb.com
=> Fix CI: change links for renamed project and fix urls

README.md
More choices for rust developers using CouchDB
=> Added Sofa HTTP Client for CouchDB

README.md
Added MAY stackful coroutine library for Asynchronous
=> Added MAY stackful coroutine library for Asynchronous

README.md
We've recently move to jenkins ci from travis thought we might as well update the badge here too!
=> Update amethyst's CI badge

README.md
This is much faster alternative to xml-rs.
=> Add quick-xml

README.md
Here is more info on the entire project
https://github.com/Joystream/joystream
=> Adding Joystream Rust Substrate runtime

README.md
Add [sharkdp/hyperfine](https://github.com/sharkdp/hyperfine/)
=> Add sharkdp/hyperfine

README.md
Consoletimer is a simple timer for a terminal (<100 LOC), written using ncurses.
=> Adding consoletimer utility

README.md
Sequoia is a cool new OpenPGP implementation. It consists of several crates, providing both a low-level and a high-level API for dealing with OpenPGP data.
=> Adding Sequoia-PGP

README.md
The Veloren GitLab repo has been moved & have accounted for it in this pr
=> Replace Veloren/game (Legacy) with Veloren/veloren

README.md
Github: https://github.com/infincia/bip39-rs
=> Adding BIP39

README.md
I updated the github action link
=> [chore] update to new github action

README.md
A basic implementation of the classical snake game.
=> Add schulke-214/rsnake

README.md
Add [nokia/memory-profiler](https://github.com/nokia/memory-profiler) to [Profiling](https://github.com/rust-unofficial/awesome-rust/blob/master/README.md#profiling)
=> Add nokia/memory-profiler to Profiling

README.md
[soup](https://gitlab.com/pwoolcoc/soup) is a very cool library that lets you query and manipulate html with an api similar to pythons beautifulsoup or jQuery
=> Add pwoolcoc/soup

README.md
https://github.com/rustasync/runtime - interchangeable api for async runtimes
=> rustasync/runtime - the async ecosystem wg runtime api

README.md
Emu is a crate I have been working on over the past few months. It is specifically a procedural macro that provides a high-level language for writing GPGPU kernels.
=> Adding Emu

README.md
[This mocking library was recently voted as the crate of the week.](https://this-week-in-rust.org/blog/2019/05/28/this-week-in-rust-288/#crate-of-the-week)
=> Add mockiato

README.md
WASM-PDF was created with Rust and wasm-bindgen: https://github.com/jussiniinikoski/wasm-pdf
=> Added WASM-PDF to Graphics/PDF section

README.md
https://github.com/holochain
holochain.org
=> Added Holochain

README.md
I also sorted the entries for this section again alphabetically as it was quite a mess.
=> Add Nimiq to cryptocurrency projects

README.md
Adding a simd-json and simsearch (name similarity not intended)
=> add simd-json, simsearch

README.md
One of the basic cryptography standards
=> Add zcash cryptocurrency

README.md
I'm not quite sure about category, since this crate on one hand wraps platform-specific APIs, but on the other hand works with all platforms listed.
=> battery crate

README.md
Here's a promising pure Rust plotting library
=> Add plotlib data visualization by milliams

README.md
Streamlib plays your favorite live streams from command line, it's still a work in progress, but the basic specification and CLI are operational!
=> Add link to streamlib

README.md
Add the Rustacean Station podcast.
=> Add Rustacean Station.

README.md
Not 100% sure if "Prompt" means what I think. Starship is a terminal prompt:
=> Add starship

README.md
phiresky/ripgrep
Luminarys/synapse
minio/minsql
seanmonstar/pretty
RazrFalcon/resvg
pingcap/grpc-rs
=> Add 6 repos

README.md
sss(so_stupid_search) is a tiny and fast string search tool for Texter(eg: programmer)
=> add so_stupid_search tool to text processing section

README.md
This library is used for generating fake data like name, email, phone number
=> Add fake-rs

README.md
Just wanted to show some love to pure Rust crypto <3, also plugging my own tool
=> Add cryptography resources

README.md
=> Add Emplace

README.md
=> Added "Image Processing" subsection under "Applications", along with its first entry.

README.md
▁▂▆▇▁▄█▁ Sparklines for Rust apps.
=> Add rspark library

README.md
Hey, would be happy if you'd like to add bandwhich. Thanks!
=> Add bandwhich

README.md
Add [etcd-rs](https://github.com/ccc13/etcd-rs)
=> Add etcd-rs

README.md
Added a link to a new crate I have recently released for genetic algorithms. Took some inspiration from this page and so wanted to be a apart of it also. The project is being developed pretty consistently so I think it would also benefit from the eyes of others, hopefully this list will give it some reach to those who can help build/make use of it!
=> Add radiate 

README.md
Reverts rust-unofficial/awesome-rust#768
=> Revert "Add the genetic programming library radiate"

README.md, src/main.rs
There might still be some that are intermittent, but this should at least fix all the ones that happen every time.
=> Fix all the current build errors

README.md
CITA is a fast and scalable blockchain kernel for enterprises. CITA supports both native contract and EVM contract, by which enterprise users can build their own blockchain applications. CITA has a unique architecture which enables enterprise users to release all their computing resources.
=> add CITA into Cryptocurrencies list

README.md
[rendered](https://github.com/rust-unofficial/awesome-rust/pull/779/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8)
=> Add graphql-client

README.md
Hi,  I'm a maintainer of fp-core.rs, bringing in functional programming interface into Rust programming language. We'd love to be on awesome-rust!
=> Add fp-core.rs

README.md
=> Add 'tiny' IRC client

LICENSE.txt
Fixes the issue I flagged in #52 around Github not noticing the license
=> Add explicit license file to make Github pick up on things

README.md
PR replacement for #795
cc @luciusmagn @palfrey
=> Update Lucid KV

README.md
dtool is a command-line tool collection to assist development:
- [Hex / UTF-8 string / binary / byte array conversion](https://github.com/guoxbin/dtool/blob/master/docs/Usage.md#hex--utf-8-string--binary--byte-array-conversion)
- [Timestamp / date conversion](https://github.com/guoxbin/dtool/blob/master/docs/Usage.md#timestamp--date-conversion)
- [Number 10/2/8/16 base conversion](https://github.com/guoxbin/dtool/blob/master/docs/Usage.md#number-102816-base-conversion)
- [Hex / base58 conversion](https://github.com/guoxbin/dtool/blob/master/docs/Usage.md#hex--base58-conversion)
- [Hex / base64 conversion](https://github.com/guoxbin/dtool/blob/master/docs/Usage.md#hex--base64-conversion)
- [URL encode / decode](https://github.com/guoxbin/dtool/blob/master/docs/Usage.md#url-encode--decode) …
=> Add guoxbin/dtool 

CONTRIBUTING.md
Refs: https://github.com/rust-unofficial/awesome-rust/pull/738#issuecomment-573468900
cc @luciusmagn
=> chore: update projects removal policy

README.md
Because apparently the gitlab ones have just stopped working...
=> Redo orbtk with Github repo/actions

README.md
Hello, I'd love to see my command-line tool _grex_ listed here. 
https://github.com/pemistahl/grex
The project is still quite young, however, it enjoys great popularity already which I'm very surprised but also very grateful about. So maybe it is a valuable addition to this list.
Thanks a lot!
=> Add CLI tool grex

README.md
=> Add s3-edit-rs

src/main.rs
=> Azure devops does 302 twice, so need to cope with that

README.md
Add bheisler/criterion.rs to [Profiling](https://github.com/bheisler/criterion.rs)
=> Add bheisler/criterion.rs to Profiling

README.md
The have moved their repository to this one now.
=> Update Nuklears main repo

README.md
Moved from m-labs to smoltcp-rs
=> Fix smoltcp

README.md
seahorse is a minimal CLI framework written in Rust.
=> Add seahorse

README.md
=> Add Spotifyd

README.md
Ms - it's a library for converting human-like times to milliseconds
`ms("1d") // will return 86400000`
=> Add ms library

README.md
It's library a made to parse UCL files into user defined structs to make configuration easy.
=> Add `uclicioius` to configuration section.

README.md
https://github.com/launchbadge/sqlx 👍
=> Add SQLx, an async SQL library which I think deserves more attention

README.md
Manages & Orchestrates JWT for user login, logout & renew. Library is async ready, has no unsafe block, and runs on stable rust.
=> Add jwtvault to the list

README.md
valora is a graphics library built specifically for generative fine art, which supports live coding, reproducible works, shaders, and more.
=> List valora

README.md
Rustation has since moved locations.
=> Rustation Update.

README.md
[nomino](https://github.com/yaa110/nomino) — Batch rename utility for developers [![Build Status](https://api.travis-ci.org/yaa110/nomino.svg?branch=master)](https://travis-ci.org/yaa110/nomino)
=> Add nomino utility

README.md
=> Add nyx-space

README.md
[sigp/lighthouse: Rust Ethereum 2.0 Client](https://github.com/sigp/lighthouse)
=> Add Lighthouse

README.md
Closes #729. Added the Awesome Rust Streaming list
=> Added "Awesome Rust Streaming"

README.md
A library for doing goldenfile testing (testing by comparing test-generated files to older files)
=> Add goldenfile (testing library)

README.md
This is my first project in rust. A simple terminal snake. More info on my repo.
=> Simple terminal snake

README.md
The prototype driver is superseded by the official driver
=> Update MongoDB link

README.md
Add project organize-rt. It's like [this](https://github.com/ManrajGrover/organize-cli), but written in Rust and has more customization.
=> Add organize-rt

README.md
[The library](https://github.com/huggingface/tokenizers) provides a fast implementation for tokenizers to use in modern NLP pipelines. Written in Rust with bindings for Python.
=> Adding Hugging Face's tokenizers to the list under Machine Learning section

README.md
A list of Rust online courses from Classpert Online Course Search
=> Add Rust Online Courses at Classpert

README.md
I just released this app. I hope you like it :)
=> Add diskonaut - a visual disk space navigator for the terminal

README.md
Code Playground is an interactive app for running Rust snippets on your mobile device - https://codeplayground.app
**Preview**
=> Add Code Playground to the learning resources

README.md
Added tendermint-rs and ibc-rs projects maintained by Informal Systems
=> Add tendermint-rs and ibc-rs

README.md
Adds a new graphql library in rust https://github.com/async-graphql/async-graphql
=> Added async-graphql

README.md
Add columnar compression and compressed-dec
=> Add compressed-vec

README.md
- https://github.com/StarArawn/harmony
- https://github.com/Ruddle/oxidator
- https://github.com/TomGillen/legion
And sort the list.
=> Add 'harmony', 'oxidator' and 'legion' into the Game Engines

README.md
Added the `oauth2`, `oxide-auth`, and `yup-oauth2` crates. I'm just not sure if this is the right spot for them
=> Added oauth2 libraries

README.md
=> Add dynomite

README.md
Yake is a task runner which runs on YAML files. It's a 100% rust CLI tool.
=> Add yake as a system tool.

README.md
Added TerrabaseDB under the databases section.
(PS: This is my first PR, tell me if something's wrong)
=> Added TerrabaseDB

README.md
Bevy is a new promising game engine and I updated also the most famous game engines badges:
* Amethyst
* geez
* Piston
=> Add Bevy game engine and update other badges

README.md
Polars is a blazingly fast in memory DataFrame library. I believe it is the most feature complete option in the Rust landscape.
=> Add crate: Polars

README.md
Hello.
I have added a library for technical analysis. Seems to be the first library of this kind in this list.
It came a long way in my projects, so I think it's ready to be published.
Placed it inside *Data processing* chapter. It seems to be correct.
=> Added YATA technical analysis library

README.md
I changed it from Travis to GitHub Actions. :)
=> Update miniserve CI

README.md
Hey :)
I just now discovered awesome-rust. If you don't mind, I would love to see [pueue](https://github.com/nukesor/pueue) being added to the list of system tools.
Cheers
=> Add pueue to system tools

README.md
Hey :)
This adds another one of my projects [comfy-table](https://github.com/nukesor/comfy-table).
It's a simplistic library to build good looking tables on your command line. The unique feature of the library is it's ability to dynamically adjust the table to the current width of the terminal.
I think this could be a nice addition and maybe help out a few people.
=> Add comfy-table to data visualization libraries

README.md
[**`binserve`**](https://github.com/mufeedvh/binserve) is a fast static web server with features like routing, templating, security, etc written in Rust.
:arrow_right: [README.md](https://github.com/mufeedvh/binserve/blob/master/README.md)
=> Added binserve to Web Servers

README.md
The project's repo https://github.com/Amjad50/plastic.
=> add `plastic` project

README.md
Adding verco utility - A simple Git/Hg tui client focused on keyboard shortcuts
https://github.com/matheuslessarodrigues/verco
https://crates.io/crates/verco
=> Add verco utility

README.md
Requesting addition of book: Rust Servers, Services and Apps to the Learning section of the listing.
=> Added a book entry to Learning section

README.md
Added the NTP client "cocom" to system-tools.
=> Added NTP client in system-tools

README.md
`Easy Rust` is a good resource to learn Rust in easy English, especially for non-native English speakers.
=> add "Easy Rust" to the Resources section

README.md
To be honest, I wasn't sure where I was supposed to stick `nixinfo`.
And there were some other projects of mine I wanted to add, I just wasn't sure of where to put them.
=> Add some of my projects.

README.md
Request to add a lib item to the readme for `Task Scheduling`. The full name is delay-timer.
=> Request to add a lib item on `task scheduling` to the readme.

README.md
Adding pepper text editor - An opinionated modal editor to simplify code editing from the terminal
https://github.com/matheuslessarodrigues/pepper
https://crates.io/crates/pepper
=> Add pepper text editor

README.md
Hi, I am Branko from Manning Publications, I thought this book of ours might be a good resource for the list.
Thanks for considering it!
=> added Refactoring to Rust

README.md
Hitbox is an asynchronous caching framework supporting multiple backends and suitable for distributed and for single-machine applications.
=> Add Hitbox to list of Caching

README.md, src/main.rs
Fixes everything new since #1080 (as new things have cropped up since that got merged)
=> Fix all the other issues with README

README.md
Fixes the issues from #1100  as well as prost rename.
=> Fixes errors with pdbtbx and prost

src/main.rs
This should make a large reduction in the number of builds that fail without retrying as most of them fail due to a lot of 429s for repos we already have checked
=> Checker: Don't retry 429's and don't worry about them if we've got a previous success

README.md
Build will still break until https://github.com/kimhyunkang/libyaml-rust/issues/13 gets resolved or we remove the badge
=> Fixes tikv build badge

README.md
[containers/youki](https://github.com/containers/youki)
=> youki - Container runtime written in Rust

README.md
Add `Data Streaming` section and introduce `infinyon/fluvio`.
=> Add fluvio to README.md

README.md
=> Add RustViz

README.md
https://github.com/zhiburt/tabled
=> Add `tabled` to CLI tools

README.md
It just adds [`static-web-server`](https://github.com/joseluisq/static-web-server) to "Web Servers" section.
=> Add static-web-server project

README.md
=> add Rbatis

README.md
=> Add rustdesk

README.md
Fixes #1042 - Add the Vaultwarden project
=> Fix #1042 - Add the Vaultwarden project

README.md
Request to add a lightweight and distributed task scheduling platform to the readme.
full name is  [delicate](https://github.com/BinChengZhao/delicate).
=> Request to add a lightweight and distributed task scheduling platform to the readme.

README.md
=> Add ozkriff/awesome-quads

README.md
Signed-off-by: Gregory Hill <gregorydhill@outlook.com>
Succeeds https://github.com/rust-unofficial/awesome-rust/pull/1066
=> add interbtc (btc-parachain) to cryptocurrencies

README.md
I have solved the issue related to the alphabetical order as suggested in the previous PR: https://github.com/rust-unofficial/awesome-rust/pull/1119#issuecomment-894793007
=> Add MetaCall to scripting section (corrected)

README.md
=> Add a powerful live stream server project.

README.md
Cross platform community web technology identification tool
Similar to whatweb and wapalyzer
=> Observer ward 0x727

README.md
+ Disclaimer: author of SeaORM
=> Add SeaQL/sea-orm

README.md
Add '0x59616e/SteinsOS' in 'Operating System'
=> Add '0x59616e/SteinsOS' in 'Operating System' 

README.md
Hi,
We just released a fully-featured e-mail parsing library for Rust and would love to have it listed on awesome-rust.
Thanks!
=> Added stalwart-labs/mail-parser to Email category.

README.md
Popularity metrics: the crate has 245.000+ downloads on [crates.io](https://crates.io/crates/scraper) and 700+ stars on [Github](https://github.com/causal-agent/scraper).
=> Add causal-agent/scraper

README.md
Hands-on Rust (https://pragprog.com/titles/hwrust/hands-on-rust/) is my book about learning Rust, through the medium of creating games. It should meet the popularity requirements: it's been in the top 5 best-sellers at pragprog.com (publisher) for 50 of the last 53 weeks, and is usually in the top 20 best selling books in the "C Language" category on Amazon.com (this changes every 5 minutes, so it's a tough one to measure - see https://www.amazon.com/dp/1680508164#SalesRank ).
=> Add Hands-on Rust

README.md
A server-side WebAssembly runtime written in Rust supporting WASI and Emscripten
=> Added Wasmer as Application

README.md
Criteria for adding: at least 50 stars on GitHub, see https://github.com/ENQT-GmbH/remoc
=> Add Network programming / RPC / remoc

README.md
Axum is quickly become popular in rust web world.
=> add axum in http server section

README.md
Add SmartCore to ML --> #1054 
Build status taken from their homepage --> https://smartcorelib.org/
+ Capitalize M in [[machine learning]
+ "See"
=> Resolve #1054

README.md
egui is a very popular and one of the fastest growing gui libraries for rust.
=> add egui to the gui section

README.md
=> Adding terminal multiplexer, zellij

README.md, src/main.rs
I think this can help people a bit more when learning Rust and using vscode :-)
=> Improve vscode plugin section

README.md
As of time of writing, totp-rs has been downloaded ~4.6k times. I think it would be a good fit here, I just hope I didn't put it in the wrong category
=> Add totp-rs

README.md
Elegant React-like library for building user interfaces for desktop, web, mobile, SSR, liveview, and more.
=> Add Dioxus Framework

README.md
Removed unneeded symbols from text
=> cleaned up typo

README.md
=> Fix typo in Habitat entry

README.md
=> Add tobaru

README.md
Added nodi to Libraries/Audio and Music
=> Added nodi to Libraries/Audio and Music

README.md
=> Add libraries that implement MQTT

README.md
=> Add `libreddit`

README.md
https://github.com/Serial-ATA/lofty-rs (4,551 downloads on crates.io)
=> Add `lofty` to Libraries/Audio and Music

README.md
Adding "So, Rust. How do I _start_?" repo 🚀 .
=> Add `rust-how-do-i-start`

README.md
Master Rust by building your own Git, SQLite, Docker or Redis from scratch
=> Add CodeCrafters.io

README.md
The library was released yesterday and just reached 50 stars:
https://github.com/stalwartlabs/mail-send
=> Adding mail-send to the E-mail category

README.md, src/main.rs
- Add link to [awesome-embedded-rust](https://github.com/rust-embedded/awesome-embedded-rust)
- Add link to [esp-rs organization](https://github.com/esp-rs)
- Add small embedded intro
=> Add embedded resources

README.md
=> iced-rs cargo link

README.md
`cfonts` is both library and application but I kept it in the application section to not double up for now.
=> Added cfonts

README.md
Added the [rust bindings](https://github.com/deltaphc/raylib-rs) for raylib.
=> Added Raylib-rs

README.md
Mprocs is a TUI for running multiple processes
=> Add mprocs

README.md
https://github.com/KusionStack/KCLVM
=> add KCL configure language

README.md
Added a link to the Rust track in-app (based on feedback in #1322)
=> Add CodeCrafters Rust track

README.md
The graph processing topic doesn't exist anymore, so I deleted it from the Table of Contents on read.me
=> Deleted inexistent graph processing

README.md
Hello - request your review and approval on the inclusion of Explore Rust on your list.
It would be a good addition under Third Party Guides section of this article. Would you like to include it in your list? We'd love to hear your feedback.
Thanks!
=> Add Kandi link

README.md
Disclaimer: core member of [SeaQL](https://github.com/SeaQL)
=> Add SeaQL crates

README.md
We've just hit 3800 stars on Github, and are soon to be releasing our version 1.0.0
=> Add SurrealDB

README.md
=> Add OpenGMK On Emulator list

README.md
A tool to find duplicate files, similar image and videos etc.
=> Add Czkawka

README.md
Cairo is the first Turing-complete language for creating provable programs for general computation.
The Cairo compiler is written in Rust, and Cairo adopts a Rust like syntax.
Cairo language has been co-invented and co-created by @liorgold2 @spapinistarkware from StarkWare.
Cairo whitepaper: https://eprint.iacr.org/2021/1063.pdf
Stark whitepaper: https://eprint.iacr.org/2018/046.pdf
=> Add StarkWare's Cairo

README.md
I've just added the sigma-rust repo. It has the required 50 stars. Thanks!
=> Add sigma-rust

README.md
Svix is great for sending webhooks and verifying webhook signatures.
=> adding Svix

README.md
[Sniffnet](https://github.com/GyulyVGC/sniffnet) is a cross-platform application to monitor Internet traffic with ease.
=> Adding Sniffnet: application to monitor your network traffic

README.md
https://github.com/fzyzcjy/flutter_rust_bridge :)
=> Add flutter_rust_bridge

README.md
https://github.com/nix-community/nurl
=> feat: add nurl

README.md
Hi there! Thanks for maintaining this. I'd like to add my MIT licensed project `Atomic-Server` to this fine list. Let me know if I should make any changes!
=> Add `Atomic-Server` to `Databases`

README.md
Beerus is a StarkNet Light Client inspired by and using helios. The goal is to provide a simple and easy to use client to query StarkNet state and interact with contracts.
Repository: https://github.com/keep-starknet-strange/beerus
=> Add Beerus StarkNet light client

README.md
Add [PoloDB](https://www.polodb.org/) to `Database`
=> feat: add PoloDB to Database libarary

README.md
This adds envy (#1364). I don't know if it is the correct position under the `Encoding` point, but I thought that's where it would fit best.
=> Add envy #HSFDPMUW

README.md
https://github.com/rust-unofficial/awesome-rust/issues/1401
=> Fix typo #HSFDPMUW

README.md
Hey babe, The new PlayStation 4 emulator dropped.
=> Add Obliteration on Emulator list.

README.md
rkyv (archive) is a zero-copy deserialization framework for Rust.
=> Add rkyv #HSFDPMUW

README.md
Hellow, it has above 50 stars now 😼🍹
=> Add vidmerger

README.md
https://github.com/comex/rust-shlex
=> Add shlex #HSFDPMUW

README.md
167 stars at the moment and steadily rising for the last two years :D
Thanks for maintaining the list!
=> Add kickoff

README.md
https://github.com/ardaku/whoami
=> Add system category and whoami #HSFDPMUW

README.md
=> Add touchHLE on emulator list.

README.md
=> Add clicky on emulator list

README.md
https://github.com/crev-dev/cargo-crev
=> Add cargo-crev #HSFDPMUW

README.md
https://github.com/hmeyer/stl_io
=> Add stl_io #HSFDPMUW

README.md
https://crates.io/crates/colorgrad
=> Add colorgrad #HSFDPMUW

README.md
https://crates.io/crates/netcdf
=> Add NetCDF #HSFDPMUW

README.md
ILLA is an open-source low-code tool that has a lot of parts written in rust. It has 4.8k stars on Github now.
=> Add ILLA Cloud to Productivity

README.md
=> Add `sysexits`

README.md
https://github.com/ParthJadhav/Rust_Search
=> Add `rust_search`

README.md
A MITM Proxy 🦀! Toolkit for HTTP/1, HTTP/2, and WebSockets with SSL/TLS Capabilities. Learning Project.
=> Add emanuele-em/man-in-the-middle-proxy

README.md
Petgraph is a graph data structure library.
petgraph provides functionalities like : 
* graph types
* algorithms
* output graphs in graphviz format.
=> Add petgraph

README.md
Adds [cacache](https://github.com/zkat/cacache-rs), a high-performance, concurrent, content-addressable disk cache, optimized for async APIs.
=> adds cacache

README.md
=> fix a typo in the readme

README.md
added __Leptos__ to the _Client-side / WASM_ section
description: Leptos is a full-stack, isomorphic Rust web framework leveraging fine-grained reactivity to build declarative user interfaces.
=> Add Leptos

README.md
rust-tools.nvim is a super helpful neovim plugin!
=> Add rust-tools.nvim

README.md
Justification:
- Downloaded over 2k times
- Multiple dependents
=> Add tiktoken-rs

README.md
[`ffmpeg-sidecar`](https://github.com/nathanbabcock/ffmpeg-sidecar)
=> feat: add `ffmpeg-sidecar` library

README.md
Adding ockam to the list. The distributed category looks a little bit different than others, what do you think about the structure of my addition?
=> add ockam to libraries/distributed

README.md
According to https://gtk.org/ GTK4 is now stable.
=> Update GTK to GTK4

README.md
Arroyo (https://github.com/ArroyoSystems/arroyo) is a state-of-the-art stream processing engine written in Rust, which allows users to write real-time data pipelines in Rust and SQL.
=> Add Arroyo to Awesome Rust

README.md
Having finally reached >2000 downloads on crates.io I would love for my project to be listed.
=> Added Cargo Commander

README.md
Artemis is a well-known library for writing MEV bots in Rust. It has 1.3k stars on github. Would be a worthy add.
=> Added Artemis

README.md
Hi 👋 I would like to add my project.
"deployment" seems like the category that fits the most 🤔
=> add release-plz

README.md
I wasn't sure if this was better under games or utilities, but I went with games since I noticed another game-related utility there (Ferium).
=> Add Ludusavi

README.md
add https://github.com/mailtutan/mailtutan
I opened a pull request before ( https://github.com/rust-unofficial/awesome-rust/pull/1498 )
I got an explanation of current policies. I've got >50 stars on the project so far and I think the project is eligible.
=> add mailtutan

README.md
This is not my project, but I have done a lot of work on it. Getting a github actions badge set up should be possible, but the owner has been somewhat inactive recently so it may take a while. Let me know if you would like me to make any changes!
=> Add entry for dfdx

README.md
Include `RustQuant` library (and new 'Finance' field under libraries).
Has 104 stars on GitHub.
=> Add RustQuant

README.md
Added graph visualiztion widget project to data-visualization scope
=> Added egui_graphs

README.md
A GameBoy Color emulator written in Rust that runs on the Web using WebAssembly
=> Added Boytacean GB emulator

README.md
Add GQL (Git Query Language) project to the list
=> Add GQL project

README.md
Not sure, where this fits best, advice welcome.
=> Add oreboot to Embedded/Firmware

README.md
Add [nt-time](https://crates.io/crates/nt-time) crate. This has been downloaded over 2,000 times on crates.io.
=> Add `nt-time`

README.md
Add [scryptenc](https://crates.io/crates/scryptenc) crate. This has been downloaded over 2,000 times on crates.io.
=> Add `scryptenc`

README.md
Add [sevenz-rust](https://crates.io/crates/sevenz-rust) crate. This has over 50 stars on Github and has been downloaded over 2,000 times on crates.io.
=> Add `sevenz-rust`

README.md
Adding new entry, given it is making good rounds, for example on [Hacker News](https://news.ycombinator.com/item?id=37049198).
=> add: machine learning / candle

README.md
Requesting you to add Frolic - An API layer to build customer facing dashboards 10x faster. Written in Rust.
Link to the open source repository: https://github.com/FrolicOrg/Frolic
We have >50 stars on github so far.
=> Added Frolic - An API layer to build customer facing dashboards 10x faster.

README.md
Added my project Skyfolder (https://github.com/mu-arch/skyfolder) to the Web Servers category.
It has over 50 stars.
=> Add Skyfolder

README.md
Add [inquire](https://crates.io/crates/inquire) crate. It has over 1,000 stars on Github and has been downloaded over 600,000 times on crates.io.
=> Add `inquire`

README.md
mailcrab entry under email tools
https://github.com/tweedegolf/mailcrab
=> Add mailcrab.

README.md
Update also badge for cloudflare/quiche
=> Add aws/s2n-quic to the QUIC section

README.md
Added link to Burn project (Flexible and Comprehensive Deep Learning Framework in Rust)
=> Update README.md - Add Burn project to ML list

README.md
Description is taken from the "About" section of the project.
=> Add MystenLabs/sui

README.md
=> Add Findex

README.md
wrestic entry under utilities.
Wrestic is a wrapper for restic built in rust.
**website**: https://wrestic.com/
**git**: https://github.com/alvaro17f/wrestic/
=> add wrestic

README.md
Add [csbindgen](https://github.com/Cysharp/csbindgen) to FFI section
=> Add csbindgen

README.md
=> Added WinterJS to the repo

README.md
[3body-lang](https://github.com/rustq/3body-lang)
The Three Body Language written in Rust
=> Add 3body-lang

README.md
Confirmed contribution criteria. 
Thank you!
=> Add UpVPN to Applications list

README.md
The star number of the project has already exceeded 50.
=> Add tencent/tquic to the QUIC section

README.md
> Our current standards are at least one of: a minimum of 50 stars on Github
As this should be fine now, re-opened from #1600
=> add lodosgroup/lpm

README.md
An operating system with a kernel using Rust from scratch and Linux compatibility.
=> Add DragonOS entry to README.md

README.md
[Tour of Rust](https://tourofrust.com/) is an amazing resource that more people should be aware of and it doesn't hurt to be included, on the contrary it's important that it gets added.
=> Added Tour of Rust on the Learning section

README.md
https://github.com/hinto-janai/festival
=> Add Festival

README.md
=> Add Chess-tui to games

README.md
https://github.com/kata-containers/kata-containers
=> Adding kata-containers

README.md
https://github.com/openobserve/openobserve
=> Add openobserve

README.md
=> Add rs_pbrt

README.md
`rustfix` [has been archived](https://github.com/rust-lang/rustfix)
=> rustfix: remove due to archiving

README.md
Hey,
I'm ddding Qrlew.
It has 3 485 downloads on crates.io.
It is released under Apache 2.0 Licence
Thank you for your consideration
Best,
Nicolas
=> Adding Qrlew - 3 485 downloads on crates.io

README.md
Added Zed to the README under the text editor category.
=> Updated README: Added Zed to Text Editors

README.md
Added [Makepad](https://github.com/makepad/makepad) to GUIs.
=> Added Makepad

README.md
Useful tool to run and debug locally Kubernetes pods.
Not sure about the category though.
=> Added mirrord

README.md
Resolves https://github.com/rust-unofficial/awesome-rust/issues/1657
=> Rename "Cryptocurrencies" section to "Blockchain"

README.md
The project meets the popularity metrics requested for the contribution
=> Added rust_kanban

README.md
Add libharu_ng to the list of PDF tools.
=> Add libharu_ng

README.md
Adding new library by cloudflare https://github.com/cloudflare/pingora
=> Adding pingora

README.md
This has 2,000+ downloads on crates.io.
=> Add abcrypt

README.md
I have added defguard - wich has a lot of rust components - but pointed to the main repository.
=> Added defguard

README.md
it is archived and also is not written in rust
=> remove leg

README.md
The name of the project has been updated to reflect its new stability and wider usage.
=> Update pg_bm25 to pg_search

README.md
Add five new crates:
* russell_lab
* russell_ode
* russell_sparse
* russell_stat
* russell_tensor
=> Add Russell (Rust Scientific Library)

.github/workflows/rust.yml, README.md
And without this you end up with outdated caches and we only really fully update on main (because that's got the creds to do a full update)
=> Because they should only slightly diff from main

README.md
Metrics: 2500 downloads on [crates.io](https://crates.io/crates/work-break)
=> Update README.md: add ShadoySV/work-break

README.md
Metric: 254 stars https://github.com/vincent-herlemont/native_db
=> docs: add native_db

README.md
Added [Vibe](https://github.com/thewh1teagle/vibe) under utilities category
=> add vibe app

README.md
Added [Mobslide](https://github.com/thewh1teagle/mobslide) under utilities category
=> add mobslide app

README.md
Hello😸 
I add [mcthesw/game-save-manager](https://github.com/mcthesw/game-save-manager) to this list. It's a game save managing tool with cloud backup.
=> Update README.md: add mcthesw/game-save-manager

README.md
Add [ynqa/sig](https://github.com/ynqa/sig)
=> Add ynqa/sig

README.md
Section: Parsing.
Item: Lady Deirdre is a framework for new programming languages and LSP servers.
=> add Lady Deirdre to Parsing

README.md
This library falls somewhere between games and network programming, I thought the games category would be the best.
As of writing:
Downloads: 7.3k
Stars: 34
=> Add Rust-GameDig

README.md
Hello,
I would like to add my https://github.com/buxx/OpenCombat (76 stars) game project to the list.
Thanks !
=> doc: update readme with open combat game

README.md
=> docs: Add OpenDAL

README.md
Migration organization 0x727 to emo-crab
=> Migration organization

README.md
`sonic-rs` is a very fast JSON library based on SIMD.
=> Add sonic-rs

README.md
No update since 7 years ago and it doesn't compile on the latest stable.
=> Remove pikkr

README.md
Based on the [Our Goals](https://doc.redox-os.org/book/ch01-01-our-goals.html) page of the Redox book.
=> Update the Redox OS description

README.md
github https://github.com/arthurhenrique/rusti-cal
crate https://crates.io/crates/rusti-cal
=> feat: add rusti-cal

README.md, src/main.rs
RustRover is an IDE by JetBrains that is free for non-commercial use.
=> Add RustRover IDE

README.md
sry, lots of issues on my last branch. should be good now(?)
=> add zenoh, zenoh-flow, foundations

README.md
spring-rs is a application framework written in rust inspired by java's spring-boot
=> add spring-rs

README.md
=> Added RMQTT project

README.md
WebSite: https://rust-exercises.com
GitHub Repo: https://github.com/mainmatter/100-exercises-to-learn-rust
GitHub Star: 3.9k
=> Add “100 Exercises To Learn Rust” under Learning

README.md
My account had been flagged about a month ago.
=> Fix some repos

README.md
`stochastic-rs`, please consider also adding to the list in the finance section. The library's main purpose is relatively stable; generating a large amount of data to train AI networks. Stars are less than 50 but downloads are over 15K. [https://crates.io/crates/stochastic-rs](https://crates.io/crates/stochastic-rs)
=> stochastic-rs

README.md
Adds [ccbrown/iocraft](https://github.com/ccbrown/iocraft).
=> add iocraft

README.md
Add [ynqa/logu](https://github.com/ynqa/logu) that has GitHub star over 50.
=> Add ynqa/logu

README.md
[penumbra-x/rquest](https://github.com/penumbra-x/rquest) [[rquest](https://crates.io/crates/rquest)] - a fast Rust HTTP client with TLS, JA3/JA4, and HTTP2 fingerprint impersonation.
```shell
sudo apt-get install build-essential cmake perl pkg-config libclang-dev musl-tools -y
cargo build --release
```
You can also use [this GitHub Actions workflow](https://github.com/penumbra-x/rquest/blob/main/.github/compilation-guide/build.yml) to compile your project on **Linux**, **Windows**, and **macOS**.
=> Add rquest: a fast Rust HTTP client with TLS, JA3/JA4, and HTTP2 fingerprint impersonation

README.md
Terminal-based, real-time traffic monitoring and statistics for your AdGuard Home instance
=> add adguardian

README.md
Updated description. We now use YARA rules for detection instead of MD5 signatures
=> Update Raspirus entry

README.md
Add my repository to the list.
[MiniRPS](https://github.com/marcodpt/minirps)
[crates.io](https://crates.io/crates/minirps)
Thank you very much for your attention @palfrey
=> Add Mini RPS

README.md
https://github.com/igorlira/dirplayer-rs
=> Add DirPlayer as Emulator

README.md
Add [Rocketmq-rust ](https://github.com/mxsm/rocketmq-rust) message queue
=> Add rocketmq rust message queue

README.md
A nice datetime library created by  BurntSushi (Andrew Gallant)
=> Add Jiff datetime library

README.md
Add https://github.com/neogenie/fastnum
=> Add fustnum

README.md
Added Limbo project to Databases section
=> Added Limbo project

README.md
I've added a vulnerability research tool that I've developed, along with a suitable application category. Cheers!
=> Add "0xdea/rhabdomancer" under the new "vulnerability research" category

README.md
https://crates.io/crates/persistent-scheduler
=> add a task scheduling libraries

CONTRIBUTING.md
=> Fix another CONTRIBUTING.md dash

README.md
Hey, This adds Pumpkin. A Minecraft server written in Rust
=> Add Pumpkin

README.md
This Repository.
https://github.com/nwiizo/cargo.nvim
=> add cargo.nvim

README.md
Hi,
I added the TailTales log viewer I've been working on for some time. Hope it makes into the list!
Thanks!
=> Added Tail Tales log viewer

README.md
https://github.com/encounter/objdiff
=> Add objdiff as Reverse engineering

README.md
https://github.com/aschey/stream-download-rs
=> add stream-download

README.md
https://github.com/cocoindex-io/cocoindex
=> Add cocoindex framework

README.md
Added a link to the official Azure SDK for Rust
=> docs: added a link to the Azure SDK for Rust

README.md
https://github.com/clitic/kdam
=> Added clitic/kdam library

README.md
Adding parallel processing crate "orx-parallel" to Concurrency section.
=> Add orx-parallel

README.md
Adding a library for working with token embeddings, and positional encoding.
=> Adding tictonix crate

README.md
Yet new, HelixDB is a fast growing (either in stars and development) and I think it deserves a place among these awesome rust projects :)
EDIT: Also fix:
- An old link for oxide-auth that broke build [42453950433](https://github.com/rust-unofficial/awesome-rust/actions/runs/15102881096/job/42453950433)
- Broken link to [illacloud.com](https://illacloud.com)
=> Add HelixDB

README.md
Tatami is a roguelike dungeon generation algorithm that creates a multi-floor dungeon layout from a series of randomly oriented, interconnected rectangles.
The library attempts to provide many of the common features found in roguelikes, such as stairs, teleporters, items, enemies and traps. It is intended to be used as a base upon which a fully featured game can be built on.
The crate has over 6,000 downloads.
GitHub: https://github.com/giraffekey/tatami
Crates.io: https://crates.io/crates/tatami-dungeon
=> Add Tatami to Game Development

README.md
Xylo is a functional programming language meant for creating procedural art.
GitHub: https://github.com/giraffekey/xylo
Crate: https://crates.io/crates/xylo-lang
Docs: https://xylo-1.gitbook.io/docs
=> Add Xylo language to Scripting

README.md
Fixes https://github.com/rust-unofficial/awesome-rust/issues/2051
=> Drop serde-yaml, add saphyr

README.md
Hello,
This pull request adds [aleph-lang/aleph_ollama](https://github.com/aleph-lang/aleph_ollama) [[aleph_ollama](https://crates.io/crates/aleph_ollama)] to the Transpiling section.
Description: AI-powered source code translation tool using local Ollama API.
Popularity: 5000+ downloads on crates.io.
Thank you for maintaining this awesome list!
=> Add aleph_ollama - AI-powered code translation tool

README.md
This PR adds two useful Rust libraries to awesome-rust:
loki_text (Text processing category)
Downloads: 3,145 total downloads
Description: Advanced string manipulation library with pattern searching, text transformation, and multiple string search algorithms
Key features:
Multiple search algorithms (KMP, Boyer-Moore, Aho-Corasick, Z-Algorithm, etc.)
Pattern searching with regex support
Text transformation utilities
Clean API design
paxit (Compression category)
Downloads: 3,414 total downloads
Description: Flexible library for compressing and decompressing files using various algorithms
Key features:
Support for multiple formats (zip, tar, gzip, xz, zst, etc.)
Modular design for easy extension
Both CLI and library interfaces
Active development
Changes:
Added loki_text to Text processing …
=> Add loki_text and paxit - String manipulation and compression libraries

README.md
Added openai/harmony - Renderer for response format used in gpt-oss.
=> Added openai/harmony to AI libraries related to OpenAI

README.md
=> Added RustNet

README.md
Adding **mathcore** to the Science section under Computation.
MathCore is a symbolic mathematics library for Rust that provides computer algebra system (CAS) capabilities. It's designed for both scientific computing and educational purposes.
- 🔢 Symbolic expression parsing and manipulation
- 📐 Symbolic differentiation and integration
- 🧮 Equation solving (linear, quadratic, polynomial)
- 🌊 Differential equations (ODEs and PDEs)
- 🔬 Arbitrary precision arithmetic
- 🚀 Parallel computation support with Rayon
- 🌐 WASM support for browser deployment
- **GitHub**: https://github.com/Nonanti/mathcore
- **Crates.io**: https://crates.io/crates/mathcore
- **Documentation**: https://docs.rs/mathcore
The library is actively maintained with comprehensive documentation and examples.
Thank you for …
=> Add mathcore - symbolic mathematics library

README.md, src/main.rs
=> Allow 202s as well

README.md
I attempted to add Fluster previously when I naively skipped over the requirements file. Now that the project meets the Github stars requirement, I'd love for it to be included here!
=> Add Fluster
