README.md
This library supports both low-level and high-level interface allowing to build either performance-critical or convenient applications. It also compiles with the latest Rust channel and will continue to do so.
=> Alternative MessagePack serialization library.

README.md
The database is Elasticsearch, only the company changed name to Elastic.
=> Elasticsearch is still called Elasticsearch

README.md
I thought of making a videos or conference section, but I think once there are more conferences or known video series then a section for those will make sense.
=> Added RustCamp 2015 talks to resources

README.md
Some projects was renamed (Travis badge depends on the correct repository name), some projects doesn't have Travis anymore.
=> Update outdated components

README.md
arrayfire-rust - rust binding for arrayfire which uses opencl underneath the hood
inquerest and queryst - url param parsers
=> Added arrayfire-rust, inquerest and queryst

README.md
I put this under Text Processing because, even though the library can be used with arbitrary iterators, n-grams are most often used with sequences of text
=> Add my `ngrams` crate to "Text Processing"

README.md
Hi,
I took the liberty of adding my project ([mdBook](https://github.com/azerupi/mdBook)) to the list of applications written in Rust.
If it doesn't belong in this list just close this PR, I would totally understand :)
=> Add "mdBook" in "Applications written in Rust"

README.md
MIO is a lightweight IO library for Rust with a focus on adding as little overhead as possible over the OS abstractions
=> Add carllerche/mio

README.md
The library is used to define packet-based protocol definitions.
[library](https://github.com/dylanmckay/protocol).
=> Add dylanmckay/protocol library

README.md
fitsio is an FFI wrapper around the astronomy library [`cfitsio`][1]
providing an interface to the standard astronomy file format "fits".
[1]: http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html
=> Add rust-fitsio

README.md
A lightweight Rust implementation of the Elasticsearch API based on Hyper.
=> Add elastic-hyper

README.md
couchdb-rs/couchdb is deprecated in favor of chill-rs/chill
=> Add chill-rs/chill

README.md
It has a 35 commits after RustyCode so I think it is fair to include it.
=> Add vscode-rust fork of RustyCode

README.md
Add link to the rust-rdkafka project (bindings to the librdkafka C client library for Apache Kafka).
=> Add rust-rdkafka bindings for Apache Kafka

README.md
Add a note that RustyCode in unmaintained.
Change links to point to VSCode marketplace.
=> Update Rust extensions for VSCode.

README.md
slackito/zip seems to be abandoned (no update in 2 years).
mvdnes/zip-rs is the most used zip crate on crates.io.
=> Updated zip library from slackito/zip to mvdnes/zip-rs

README.md
Surprised that this wasn't already on here. I've been using this for native Gzip compression since it released last year.
=> Add Zopfli to Compression

README.md
I had to rename the repository because there was an existing crate.
=> Rename woodpecker to drill

README.md
My PDF library has currently more features than kaj/rust-pdf, which is currently the only listed library. So I thought it would be fair to include it on this list.
=> Add sharazam/printpdf as PDF library

README.md
Added my [static_assertions](https://crates.io/crates/static_assertions) crate in a new category for static analysis tools.
=> Add static_assertions crate

README.md
A Travis CI badge is omitted because this library can not be build on Travis CI. See the details for https://github.com/pikkr/pikkr/pull/3
=> Add pikkr/pikkr

README.md
More information on this project is available here:
https://www.vandenoever.info/blog/2017/09/04/rust_qt_binding_generator.html
https://www.vandenoever.info/blog/2017/09/10/time_for_rust_and_qml.html
=> Added the new Rust Qt Binding Generator hosted by KDE.

README.md
Just want to add my crate [lotabout/skim](https://github.com/lotabout/skim) into the list.
=> Add lotabout/skim to the list

.travis.yml, README.md
- Fixes a mistake in skim's Travis tag, where the picture was being taken from just `travis-ci.org` while the link lead to `api.travis-ci.org` causing double 302 response.
- Changed the website of thrussh to the github repository, as the original website doesn't exist anymore while the repository still does
- Whitelisted https://sciter.com/ , they are doing something weird with their website, but it still works
=> Try fixing all issues

README.md
[snatch](https://github.com/derniercri/snatch) is no longer maintained.
[zou](https://github.com/k0pernicus/zou) is an active fork of snatch.
=> Replace snatch with zou

README.md
* [liuchong/docker-rustup](https://github.com/liuchong/docker-rustup) — a multiple version (with musl tools) Rust Docker image
My docker images, automatic builded on docker cloud, triggered by ./build.sh
=> Add my docker images:

README.md
According to [snaek repo](https://github.com/mitsuhiko/snaek) snaek is deprecated in favor of milksnake
=> Replace snaek with milksnake

README.md
The old link leads to a repo that only gives a new link. I also updated the travis-ci to point to the correct project.
=> Update vulkano with the new repository.

README.md
- mpw-rs is now transferred to the Rust community of Hyderabad.
- Fixes the repo and build status links to point to the new repository.
Signed-off-by: Rahul De <rahul080327@gmail.com>
=> Fix URLs for mpw-rs

README.md
@tupshin's Cassandra binding is no longer maintained (and does not currently build!), but there is a maintained fork. Update the README to point to the new one.
=> Replace old Cassandra binding with maintained one.

README.md
Relm is an asynchronous, GTK+-based, GUI library inspired by Elm
=> Added reference to Relm (Gtk lib)

README.md
Add github.com/casey/just to development tools.
It's a command runner with a nice file format for saving project-specific commands. I didn't include a link to the crate, since as a binary that doesn't seem super useful.
I'm not sure what the best short description is "A handy command runner for project-specific tasks" seems good, but I'm certainly open to suggestions.
Thanks!
=> Add just to development tools

README.md
Cross-platform, zero-copy, and endian-aware binary parsing.
=> Add m4b/goblin.

README.md
Tcod-rs: Bindings for the libtcod (c++/python, mainly) roguelike library. Added under Game development section.
=> Add Tcod-rs under Game development

README.md
I put it at the top of category because it seems to me that **Utilities** category is sorted by repo-name not author. Hope that's ok.
PS: my first time PR
=> Add hyperfine - command-line benchmarking tool

README.md
Both clients could be used with Rust Language Server, and both are implemented in Rust.
=> add LSP clients for Vim/Neovim and Kakoune

README.md
**crates** is an extension for crates.io dependencies. Aims to help developers to manage dependencies while using _Cargo.toml_. It is only helpful if you are using dependencies from _crates.io_.
=> crates extension added for vscode

README.md
the github is just a mirror so pointing people there seems wierd.
=> Change redox-os link

README.md
Under development tools, add a new subsection to transpilers from C to Rust. In this section, link to Corrode and C2Rust transpilers. Transpilers help developers migrate to Rust by automatically translating C code into (initially unsafe) Rust code that can be further refactored into safe and idiomatic Rust.
=> Add new subsection for transpilers

README.md
`duct` is somewhat redundant with the `subprocess` crate, and I don't know what the process is for including redundant things, but I figured I'd submit a PR :)
=> add a link to the duct crate

README.md
This is the library [`exa`](https://github.com/ogham/exa) and Rust coreutils [`ls`](https://github.com/uutils/coreutils/blob/master/src/ls/ls.rs) are built on. It's pretty cool in my opinion.
=> Add rust-term-grid library to TUI section

README.md
There's a space between the ] and the ( of this link, so it doesn't render as a link on GitHub. This should fix it! ❤️
=> Fix markdown by removing a space in a link

README.md
So the TravisCI icon is green again.
=> Fixed broken rusters link, and updated redirections.

README.md
Adds two new crates:
- parallel-getter
- progress-streams
`progress-streams` is a direct dependency of `parallel-getter`, to provide the callback functionality. We needed to develop the `parallel-getter` crate because downloading `deb` archives from an APT repo with a single GET request is really slow (500KiB even if you have a 50MiB connection). The `parallel-getter` crate was needed for our `debrep` utility to speed up the repo sync and fully utilize all of our available bandwidth. Mirrors are also supported to speed up downloads. This and the url-crawler may eventually be the basis for an `apt` replacement, should the Pop project get around to replacing it.
=> Add parallel-getter & progress-streams from Pop repos

README.md
This PR adds the `har-rs` lib and a corresponding new section for HAR/HTTP Archive Format files used by Charles Proxy, Google Chrome etc.
=> Add har-rs

README.md
This PR adds the `postman-collection-rs` lib and a corresponding new section for Postman Collections.
It also adds a Travis CI badge (as a separate commit) which was missing in #554.
=> Add postman-collection-rs

README.md
I'm reasonably certain that yaserde belongs under xml, rather than yaml.
=> Move yaserde from yaml to xml

README.md
Adds a small crate for processing lines of text as bytes rather than `String` due to faster throughput.
=> Add whitfin/bytelines

README.md
Imageproc library is now a library by PistonDevelopers based on Image library the one from the old link died years ago.
=> Replacing link to imageproc library

README.md
Add section that describes libraries that cover signal buses or standards used in automotive.
=> Add automotive section

README.md
I believe this was mistakenly added under Webpack in #597.
=> Move cargo-expand under Cargo section

README.md
* remove absent `pop-os/pop-recovery`
* update link `rust-lua`
* update link `human-panic`
* update link `libui-rs`
* update link `rustlings`
* update link `Qt`
=> Fix CI: remove absent project and change links for renamed projects

README.md
The extra forward slash in the the img tag's src attribute was creating
a broken link.
=> Removed extra forward slash from src attribute.

README.md
`netsim` is a crate for simulating networks for the sake of testing network-oriented Rust code. You can use it to run Rust functions in network-isolated containers, and assemble virtual networks for these functions to communicate over.
=> Add network simulation library

README.md
tch-rs provides some rust bindings for PyTorch so I've added it to the machine learning section.
=> Add tch-rs.

README.md
As shown in [README](https://github.com/BurntSushi/rust-cbor), cbor is unmaintained and serde_cbor should be used instead.
=> Replace cbor with serde_cbor

README.md
NNG is the successor to Nanomsg and, given that [Nanomsg is actively recommending switching to NNG][1], it seems like it would be a good idea to have it on this list. Thanks!
[1]: https://github.com/nanomsg/nanomsg#support
=> Add neachdainn/nng-rs

README.md
Hi! This PR adds a link to [Cloudsmith](https://cloudsmith.io), which is a package management service SaaS. It's commercial, but it is completely free for open-source and it has generous free tiers otherwise. It has first-class support for Cargo/Rust (and many other package formats, such as Npm), plus org/teams management, granular access controls, private repositories, repository-specific entitlements, a worldwide content distribution network, webhooks, access logs, etc. As this is the first of its kind, I've also created a new section entitled "Registries" for review. Thank you. :-)
Full disclosure: I work at Cloudsmith. \o/
=> Added Cloudsmith (Cargo Registry) + New Section

README.md
Crate that integrates Rust and QML via QMetaObjects.
Side note: I noticed that Qml-Rust is at the bottom of the Qt section, unlike the other crates whose names start with q (which are at the top of the section). Should I move this up as well?
=> Add woboq/qmetaobject-rs

README.md
Google announced at Google IO 2019 that their Chrome OS VM used for running Linux apps on Chrome OS is written in Rust. Source: https://youtu.be/pRlh8LX4kQI?t=483
=> Added CrOSVM

README.md
I missplaced it under Vulkan, sorry! Also added Travis ci badge.
=> Move WASM-PDF under PDF section

README.md
An example of using a shared Rust lib for Android and iOS using rust-swig and cbindgen respectively.
https://github.com/i-schuetz/rust_android_ios
=> Add Android / iOS example repo

README.md
Hey,
Including Rust for professionals link.
It's a link with Rust examples and comparisons with other programming languages like JavaScript, TypeScript, etc.
=> Add Rust for professionals

README.md
This pull request adds fields under the [Audio](https://github.com/rust-unofficial/awesome-rust#audio) and [Emulators](https://github.com/rust-unofficial/awesome-rust#emulators) sections containing the entries for the [Ruffle](https://github.com/ruffle-rs/ruffle) and [Spotify TUI](https://github.com/Rigellute/spotify-tui) applications.
=> Add Ruffle and Spotify TUI

README.md
Adding a link to https://rustbeginners.github.io/awesome-rust-mentors/ under Resources.
=> Add awesome-rust-mentors to Resources

README.md
I removed rise-ui due to lack of development, and instead added OrbTk, which looks promising if one doesn't mind the dependency on SDL2
=> GUI: remove rise-ui, add OrbTk

README.md
[Rust Search Extension](https://github.com/Folyd/rust-search-extension) is a handy browser extension to search crates and docs in the address bar (omnibox).
More info you can check here: [/r/rust post](https://www.reddit.com/r/rust/comments/dp1ru6/i_published_a_handy_chromefirefox_extension_to/).
=> Add rust-search-extension

README.md
Add the link to **GitHub Actions for mdBook (rust-lang/mdBook)**
> Setup mdBook quickly and build your site fast. Linux (Ubuntu), macOS, and Windows are supported.
- repository: https://github.com/peaceiris/actions-mdbook
- marketplace: https://github.com/marketplace/actions/mdbook-action
=> Add mdBook setup GitHub Action

README.md, src/main.rs
Travis build badges that no longer refer to a build return 200, but have a Content-Disposition header that says `inline; filename="unknown.svg"` and so we can detect them with some changes to the checking tool. This builds on top of #804 so that we have an otherwise clean README. https://travis-ci.org/rust-unofficial/awesome-rust/builds/639610636 demos the failure case.
=> Detect "unknown" status Travis builds

README.md
Minor items, but good to fix
* rust-lua naming pointed to old name for user
* fp-core had 301'ing build badge (from #780)
=> Couple more README fixes

README.md
[This](https://github.com/ozankasikci/rust-music-theory) library and potential future libraries won't fit under the Audio category, hence i felt the need to update the `Audio` headers to `Audio and Music`.
=> Add Rust Music Theory library, update Audio headers

README.md
The only listed window manager was way cooler, which is no longer written in Rust: http://way-cooler.org/blog/2019/04/29/rewriting-way-cooler-in-c.html
https://github.com/way-cooler/way-cooler
=> Remove windowmanagers section

README.md
EDN-RS: is great for microservices written in rust that are in a Clojure environment, as Clojure's most used data notation is EDN. Parser is highly usable for our current projects and serializer will be implemented with Datomic client, in the near future.
Hiccup: Templating HTML, and also XML,  engine that prevents unclosed tags problems. It is inspired by the clean and simple syntax of Clojure's Hiccup Lib
=> Includes EDN-RS and Hiccup

README.md
Hey! 
GTSA project it's fasto solution for passing gelf messages to Sentry.
=> Add GTSA project

README.md, src/main.rs
IIRC Github does default sensibly to just master, but Travis will default to "last build, on any branch", which means you get marked as failing even if all you've got is a dodgy unmerged PR. This PR checks that both Github Actions and Travis build badges specify a branch, and fixes all the cases for both. I've also linked a few of the Github actions buttons back to their workflow pages.
=> Make sure Travis/Github build badges have a branch

README.md, src/main.rs
Turns out that "Content-Disposition" isn't entirely reliable, but searching the SVG is. Zola was a bad instance of this, so I've fixed the build badge for that.
=> Better unknown travis detection

src/main.rs
e.g https://travis-ci.org/rust-unofficial/awesome-rust/builds/655410445
=> Github workflows have started to do 406, unless we add an explicit image to the Accept header

.gitignore, .travis.yml, Cargo.toml, results/.gitignore, src/main.rs
Mainly because I keep getting annoyed by the build being marked as "failed" when what's actually happened is one of the sites has had a bit of a wobble. One-off wobbles shouldn't worry us, it's when something stays down or moves then we need to be concerned.
This PR redoes the results.yaml so it stores in a subdirectory we can cache in Travis and in theory therefore refer to in later builds. It now also stores various bits of data (last updated, last working, any error messages, etc) in the output file as opposed to just "working" or "failed". It should only fail if a URL is either a) brand new and not working or b) hasn't been working for at least 3 days.
=> Cache the results of getting links across Travis build and only re-check every so often

README.md
I added my own crate, bigbang, to a new Simulation section. It _could_ go with Geospatial, but it isn't really the same as those other crates in that category. There are other simulation crates out there, as well, that could help populate this section.
=> Add bigbang to crates and add Simulation section

README.md
zoxide is a CLI utility that tracks your directory usage, allowing you to quickly `cd` to anywhere on your filesystem using just part of the directory name.
=> Add zoxide under System Tools

src/main.rs
This would fix #859 (429 errors from Github) but I don't have enough permissions to add a new secret value to Travis.
@luciusmagn Any thoughts? Do you have enough access for this?
=> Support optional use of Github secrets to workaround rate limits

README.md
The `gfx-rs` group is investing a lot of effort in WebGPU with their library, `wgpu`. `wgpu` is the lowest-level "safe" graphics available, runs both on and off the web, and is generally more approachable to more kinds of users than `gfx-hal`.
=> Add link to gfx-rs/wgpu library

README.md
I'm not affiliated with mun, just stumbled across them.
It looks like they're still WIP / not committing to production stability. However, the language has had several releases, has active development, and is already a great example of a scripting language implemented in Rust.
I wasn't sure whether to list the github page or their website, https://mun-lang.org/. I went with the github page to match existing entries.
=> Add mun-lang to Scripting section

.travis.yml
This seems to get the build of the tool down from ~3m to ~1m15, and seems to work a lot better than the default Rust artifact caching (also has a limit to cache size which should result in it throwing away old data eventually, unlike stock cargo work)
=> Add sscache support

README.md
Added the `Linq-in-Rust`, a library brings a macro for C#-LINQ-like expressions. Thank you.
=> Add Linq-in-Rust

README.md
Sled: A (beta) modern embedded database.
github: https://github.com/spacejam/sled
crate: https://crates.io/crates/sled
Should be good to have in the list.
=> Add sled to Database category

README.md
Travis builds are not available. Originally:
```markdown
* [rstest](https://crates.io/crates/rstest) — Fixture-based test framework for Rust [<img src="https://api.travis-ci.org/la10736/rstest.svg?branch=master">](https://travis-ci.org/la10736/rstest)
* [ruspec](https://crates.io/crates/ruspec) — Write like Rspec testing framework with rust [<img src="https://api.travis-ci.org/k-nasa/ruspec.svg?branch=master">](https://travis-ci.org/k-nasa/ruspec)
```
=> Add `rstest` and `ruspec` testing frameworks

CONTRIBUTING.md
As offered I updated the contribution guide to use the repository link as a primary link and add an optional `crates.io` link. I hope that's ok.
=> Updated the contribution guide with a new template

README.md
The `nats` crate is the official client for the [NATS](https://en.wikipedia.org/wiki/Cloud_Native_Computing_Foundation#NATS) messaging system.
https://nats.io
=> Add NATS client to the Network Programming section

README.md
I think listing [Ox](https://github.com/curlpipe/ox) (2k+ stars) as a Rust text editor would be a good addition.
Continuation of #996.
=> Add ox editor

README.md
TerminusDB's storage is implemented in Rust - I am including in the list of databases as it may be of interest to the broader Rust community.
=>  Adding TerminusDB to list of Rust Databases

README.md
The link that points to the holochain repo has been updated to point to the new repo which is actively being maintained. The link and build status of the old repo have been kept, the new repo doesn't provide build status, so it's not been included.
=> Added new link of the holochain repo, also kept the old one

README.md
Phala is a rust based confidentiality layer for Substrate and Polkadot based blockchains
=> Add Phala Network to cryptocurrencies

README.md
It moved from Travis to GitHub Actions
=> Fix TerminusDB CI link of TerminusDB storage engine

README.md
cargo-dinghy is a cargo extension to simplify running library tests and benches on smartphones and other small processor devices.
=> Add cargo-dinghy to Testing

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, README.md, src/main.rs
This PR does a couple of things, resulting in a working Github Actions build
* It upgrades a bunch of packages, mostly to solve the `error reading DNS system conf: Error parsing resolv.conf` error that was occurring on earlier Github actions builds
* It fixes all the current bad urls in README.md
* It adds lots of caching to the Github actions build, including some fun with `always-upload-cache` and `RANDOM` so that if we manage to get some items for the results cache, but it then borks later on, we a) still store the ones we managed to get and b) if we re-run the build, can repeatedly re-store the result file and incrementally get towards a working build. I did this with this one to get a green build, and may well be needed when this gets merged.
To clarify, this isn't me intending on …
=> Fix GitHub build

.github/workflows/approve.yml, .github/workflows/rust.yml
Needs #1097 to fix the build issues.
This PR does two things:
- Enables cron job for automatically re-testing the list each night
- Adds https://github.com/marketplace/actions/automatic-approve to auto-approve for running in Github actions any PRs that make no changes to either the `.github/workflows` or the Rust code for checking things (i.e. anything that could enable abusing the repo to run crypto miners)
After this, it's probably worth disabling the Travis runs, requiring Github actions to work to merge something, and maybe also needing a branch to be up-to-date to merge?
=> Cron jobs to auto-approve for running, and retest the list

README.md
_Note: I am the main author of the proposed project_
PDBTBX is a library for handling PDB/mmCIF files used for saving 3D models of proteins. These 3D models are very common in [structural bioinformatics/biology](https://en.wikipedia.org/wiki/Structural_biology).
=> Added PDBTBX

src/main.rs
This means that if for example you've got a new link, we check that first. This means we avoid hitting 429 issues on those due to re-checking other ones that are fine.
=> Checker: Check the oldest/unchecked ones first

README.md
Note: I am the main author of the proposed project.
[Datafuse](https://github.com/datafuselabs/datafuse) is a Real-Time Data Processing & Analytics DBMS with Cloud-Native Architecture written in Rust, inspired by ClickHouse and powered by arrow-rs, built to make it easy to power the Data Cloud.
Datafuse is build as an open source and enterprise-grade alternative to Snowflake.
=> Add Datafuse to Database

README.md
`m2cgen` is a lightweight library written in Python with command line interface which allows to transpile trained machine learning models into a native code of Rust programming language. Examples of generated Rust code can be found [here](https://github.com/BayesWitnesses/m2cgen/tree/master/generated_code_examples/rust).
=> Add m2cgen for transpiling ML models into Rust code

Cargo.lock, Cargo.toml, README.md, src/main.rs
The CONTRIBUTING.md says "please pay attention to the alphabetical ordering", but it hadn't been paid attention to for some time. This PR makes the build checker check the order and spit a diff for out anything in the wrong order. It also reorders the README to have the correct order.
=> Sort the README and enforce it with the checker

README.md
Hi! [gfold](https://github.com/nickgerace/gfold) is a CLI tool to help keep track of multiple Git repositories. It currently has 55 GitHub stars, and nearly 800 downloads on [crates.io](https://crates.io/crates/gfold). Please let me know if there's anything I can do to help get `gfold` added, and thank you in advance!
=> Add gfold to System tools

README.md
The previous link leads to an old archived version of the GTK bindings which are depreceated. I removed it and linked the GTK3-rs Gtihub page.
=> fix: Gtihub link leads to an archived repository of the depreceated GTK binding. Updated it to new-ish gtk3 binding

README.md
Added:
- `arangors` the most popular ArangoDB driver
- `aragog` an object document mapper for ArangoDB handling graphs and relations
I suggest deleting the `rincon` reference which has not been update in nearly 3 years and has no documentation or examples
=> Add Arangors and Aragog

README.md
[ytop](https://github.com/cjbassi/ytop) is no longer being developed and the docs lists [bottom](https://github.com/ClementTsang/bottom) as a alt project. Fixed #1087
=> Replaced ytop with bottom

README.md
Adding the [AWS Lambda runtime](https://github.com/awslabs/aws-lambda-rust-runtime) crate by AWS Labs to the listing to help manage writing Lambda functions with Rust.
=> Add AWS Lambda Rust Runtime to list

README.md
Safe, fallible, stack-only alternative to `BTreeSet` and `BTreeMap`. Docs [here](https://docs.rs/scapegoat/latest/scapegoat/).
=> Add scapegoat to data structures

README.md
Rust bindings for MDBX —  fork of mozilla/lmdb-rs with patches to make it work with libmdbx.. Fast, compact, powerful, embedded, transactional key-value database, with permissive license.
=> Adding  libmdbx-rs fork

README.md
There are a couple of different categories under the testing section.
This subdivides that section to make things easier to find.
Also add link to #test crates list. This seems almost as popular as
#testing and not all projects have both tags.
=> Subdivide testing section

README.md
Bartib is a simple timetracker for the command line written in rust
=> Add Bartib

README.md
I added CHIP-8 section in Emulators with 2 excellent repos.
[CHIP-8](https://en.wikipedia.org/wiki/CHIP-8) is a nice place to start when learning emulation
=> Add CHIP-8 section in Emulators

README.md
Criteria for adding:
BlueR was called BLEZ and located at https://github.com/surban/blez before it became the official Rust binding for BlueZ and moved to their GitHub organization.
Together the old and new repository have 40 + 28 = 68 stars.
=> Add Network programming / Bluetooth / bluer

README.md
This PR adds `cargo-all-features` to the `Build system` section.
I'm neither a maintainer of `cargo-all-features` or some rust guru but as a rust lover and community member I have found this crate very useful and lovely as to leveraging the `if it compiles, it runs` sentiment for any kind of feature combinations and it provides another level of checks to reduce tickets, times worrying & prying and needed patches for releases.
I'm not sure if I chose the truly correct section but it seemed to fit the most.
Any feedback is very much welcome 🦀 🥂 
__Edit__:
As for stats:
- Github starts: 68
- Crates.io
* recent: 9'069
* all time: 43'450
> This does not include any downloads from things like `cargo-binstall` or `cargo-quickinstall`
=> feat(build-system): add cargo-all-features

README.md
Add curated list to awesome-rust. It contains index of various books and quite a few are not listed in here even though seem good (High Assurance Rust, Official Async Book etc.). I see that repo accepts curated lists, so this shouldn't be a problem.
=> Add lborb to learning section

README.md
Added fleet to build system - 🚀 The blazing fast build tool for Rust.
=> Add fleet-rs to build system

README.md
Adding inspektor to the security tools list. 
Inspektor is a database protocol-aware proxy that is used to enforce access policies.
=> add inspektor to the security tools list

README.md
Fred is a high level Redis client built for Tokio. The repository linked here is the new location, and the old repository can be found [here](https://github.com/azuqua/fred.rs).
=> Add fred to Redis clients

README.md
[Rustix](https://github.com/bytecodealliance/rustix) is a library that provides safe Rust bindings to POSIX/Unix/Linux/Winsock2 syscalls.
=> Add rustix to Unix-like.

README.md
This repo moved and now it's triggering an ❌ in the GitHub Actions for this repo.
=> Update socketcan-rs URL

README.md, src/main.rs
Prettier is an opinionated code formatter https://prettier.io/
- Added `Formatters` category
- Added [`Prettier Rust`](https://github.com/jinxdash/prettier-plugin-rust)
- Moved `rustfmt`, `dprint`
- Changed `rustfmt` description `+= " maintained by the Rust team and included in cargo"`
- Added [`Prettier - Code formatter (Rust)`](https://marketplace.visualstudio.com/items?itemName=jinxdash.prettier-rust) VSCode extension
=> Add prettier

.github/workflows/lint.yml, .github/workflows/rust.yml
Fixing the issue from https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Upgrade actions

README.md
[cairo-rs](https://github.com/lambdaclass/cairo-rs) is a Rust implementation of the Cairo VM. Cairo is a programming language for writing provable programs, where one party can prove to another that a certain computation was executed correctly. Cairo and similar proof systems can be used to provide scalability to blockchains.
`cairo-rs` offers a very efficient Cairo virtual machine, and will be used by StarkNet sequencer.
=> Add cairo-rs - Rust implementation of the Cairo VM

README.md
Hello!
I would like to suggest adding [WhatBPM repo].
[WhatBPM] is a daily updated information resource for [EDM] producers, answering questions such as
what [BPM] / [root note] / [key] / [track length] to use for a new production, what [labels][label] to look at, what [EDM] genres are the most trending, and so on. 
The daily analytics provided by [WhatBPM] is based on publicly available data, such as Beatport and Spotify.
It is made with Rust. 
It uses GitHub Actions to update its content daily.
It is served using GitHub Pages.
It has already been supported by such artists as: [nanobii], [Somnia], [Slava Basyul].
Thank you in advance.
[WhatBPM]: https://sergree.github.io/whatbpm/
[WhatBPM repo]: https://github.com/sergree/whatbpm
[EDM]: …
=> Add WhatBPM

README.md
As mentioned in the README of [the GitLab project](https://gitlab.com/susurrus/serialport-rs), serialport-rs has been moved to GitHub.
=> serialport-rs moved to GitHub

README.md
This pull request removes repositories made by Arvan Cloud. Arvan cloud has a well known player in restricting Iran's internet, creating spywares against people and helping Islamic Republic of Iran in suppression of  women's rights. Even if their crates does not contain any obvious treats for non-Iranians, they could use future updates to trojan-horse malicious code into countless servers and computers.They have already been sanctioned by EU.  I hope limiting this company's reach could  make this ecosystem far-safer for everyone.
Here are some links to back up some of my claims:
https://netzpolitik.org/2022/nach-investigativer-recherche-eu-verhaengt-sanktionen-gegen-arvancloud/ https://iranwire.com/en/politics/110067-arvancloud-a-firm-sanctioned-for-helping-iran-to-create-a-sanitized-inter …
=> remove repos made by hostile developers

README.md
https://github.com/tamasfe/taplo
Reasonably popular TOML toolkit that comes with a `jq`-like CLI tool.
=> Add `taplo`

README.md
Hello,
I have added `async-openai` under a new  sub category `OpenAI` under existing `Libraries --> Artificial Intelligence` - please let me know if it can be categorized better.
Following are the stats as of today:
- Stars 57 https://github.com/64bit/async-openai
- Downloads 2058 https://crates.io/crates/async-openai
Thank you!
=> Add async-openai under Artificial Intelligence

README.md
Add [Kaioshin](https://github.com/keep-starknet-strange/kaioshin).
It is a Rust project, using substrate framework. 
Here is the architecture of Starknet sequencer:
=> add Kaioshin - Substrate based sequencer for Starknet

README.md
travis-ci.org links are all now assortedly 404'ing or 301'ing to the travis-ci.com homepage. Some of the projects probably have newer better build badges, but that's a _lot_ of work that I'm just not going to get around to doing. This PR deletes all of them, and future folks can add some back where relevant.
=> Remove all the travis build badges

README.md
Adding [cargo-udeps](https://github.com/est31/cargo-udeps), a tool to find unused dependencies.
I put it in the ["Build system" section](https://github.com/rust-unofficial/awesome-rust/tree/ccf576800c1fafffae81933e9d51b71491424f67#build-system) because similar tools (e.g. [kbknapp/cargo-outdated](https://github.com/kbknapp/cargo-outdated)) are listed there too. Happy to put it anywhere else if that makes more sense.
I followed the format specified in the [Contributing Guidelines](https://github.com/rust-unofficial/awesome-rust/blob/ccf576800c1fafffae81933e9d51b71491424f67/CONTRIBUTING.md) even though most entries in this section don't. Happy to adjust if that's preferred.
=> Add cargo-udeps

README.md
The following pull requests adds [decancer](https://github.com/null8626/decancer) ([crates.io](https://crates.io/crates/decancer)) package to the Text Processing category.
It should be eligible for `awesome-rust` as it has 57 stars at the moment - and other contributing aspects too like:
- 1.1k downloads (all time) on `crates.io`
- 2.1k downloads (per month) on `npm` (it's official Node.js binding)
- it also has an [unofficial Python binding](https://github.com/Jonxslays/decancer_py) too
Again, thank you for this *awesome* curated list of *awesome* projects! ❤️
=> feat: add decancer to Text Processing

README.md
Add skillratings crate to game development category, useful for developing multiplayer games with leaderboards or matchmaking
- https://github.com/atomflunder/skillratings
- https://crates.io/crates/skillratings
=> Add skillratings

README.md
- Introducing a new **Payments** category to feature rust projects in the payments ecosystem. 
- Adding **Hyperswitch**, an open source payments orchestrator, that lets your project integrate with multiple payments processors, using a single API.
=> add Hyperswitch

README.md
I want to add my framework [`phper`](https://github.com/phper-framework/phper) in FFI/PHP category in README. :-)
=> Add phper to FFI in README.

README.md
Add innernet an overlay or mesh network that uses Wireguard to Awesome Rust.
=> Add innnernet to Awesome Rust(Unofficial)

README.md
[Aladin Lite](https://github.com/cds-astro/aladin-lite) is a web application developed at CDS for visualizing spatial and planetary image surveys in different wavelengths and projections.
The project was initially developed in 2013 in pure javascript using 2D canvas rendering. Since a few years, a core rust library compiled to WebAssembly has been developed to improve the performance and add new features such as:
* multi all sky projections support
* usage of WebGL for rendering the HEALPix tile images as well as generic FITS images
* adjust the rendered tile pixels on the client side (color, saturation, brightness changes, tranfert function application)
* enhanced core functionalities thanks to the reuse of other rust libraries developed at CDS …
=> Add Aladin Lite spatial images visualizer

README.md
Add Holo (disclaimer: my project!) and RustyBGP to the new "Routing protocols" category.
Similar projects in other languages:
* https://github.com/FRRouting/frr
* https://github.com/osrg/gobgp
=> Add routing protocols projects

README.md
Include the apca crate in the listing of "Finance" crates in the README. The crate provides bindings to the Alpaca trading and realtime data APIs offered by https://alpaca.markets/
=> Include apca crate in README

README.md
[vue-skia](https://github.com/rustq/vue-skia)
Skia based 2d graphics vue rendering library. It is based on Rust to implement software rasterization to perform rendering.
=> Add vue-skia

README.md
I have included the eBPF section to the libraries in this commit. It comprises three distinct Rust libraries, which could be helpful for the project.
=> Update README.md to add the eBPF section

README.md
exa is unmaintained. The repo now suggests switching to eza
[eza-community/eza](https://github.com/eza-community/eza)
=> Replace exa with eza

README.md
It's stable, actively maintained, and has more than 2000 downloads on crates.io.
Thank you very much for maintaining this list!
=> Add `imap-codec`

README.md
Euclider & Tray_rust appear to be outdated as I was unable to make them run in the latest version of Rust.
Fortunately, I came across another library that does work - dps/rust-tracer.
Let's include it here.
Thank you.
=> Add dps/rust-raytracer

README.md
tui-rs is no longer maintaned https://github.com/fdehau/tui-rs/issues/654).
Replaced tui-rs with suggested fork ratatui (https://github.com/ratatui-org/ratatui)
:)
=> Replace unmaintaned tui-rs with active fork: ratatui

README.md
This PR adds [Rinf](https://github.com/cunarist/rinf) framework that connects Flutter and Rust
=> Add Rinf: Rust in Flutter

README.md
I had to introduce an according category as no application category matched this project.
Buffrs is a package manager for protocol buffers and gRPC architectures. It allows engineers to create semantically versioned libraries and apis in protobuf and lint and publish them using `buffrs`. The project ships a cli and soon a registry component.
It is a great learning resource for others (and a way easier one to learn than cargo!) on how to build a package manager in rust and: In the protocol buffers ecosystem this actually fills in a big gap of tooling. Making it visible for people should drive adoption, get people to write their ideas, usecases and feature requests to us.
=> Add `helsing-ai/buffrs` and add `### Package Managers`

README.md
This adds [Rauthy](https://github.com/sebadob/rauthy) to the README.
OpenID Connect Single Sign-On Identity & Access Management  written in Rust.
=> Add Rauthy OIDC IAM

README.md
Would like to add [my own] [binary exploitation tool](https://crates.io/crates/xgadget) to the security section.
* Meets the star and download threshold in the this repo's `CONTRIBUTING.md`
* MIT licensed
Thanks for maintaining this list!
=> Add xgadget to security tools, alpha-sorted by repo/proj

README.md
Adding [rnote](https://github.com/flxzt/rnote).
=> rnote: adding

README.md
The previous "Polkadot" [link](https://github.com/paritytech/polkadot) points to a repository that is no longer maintained. The README says _In order to streamline our development process and foster better contributions, we have merged three separate repositories Cumulus, Substrate and Polkadot into a single new repository: [the Polkadot SDK](https://github.com/paritytech/polkadot-sdk)_. I think it makes sense to link the new repository instead
=> Fixing depracated polkadot repository

README.md
enum-map moved to codeberg: https://github.com/KamilaBorowska/enum-map
=> update link to `enum-map`

README.md
since spotify-tui seems to be [unmaintained](https://github.com/Rigellute/spotify-tui/issues/1000), there's [spotify-player](https://github.com/aome510/spotify-player) which seems to be very good.
depends on: https://github.com/rust-unofficial/awesome-rust/pull/1636
=> replacing `spotify-tui` with `spotify-player`

README.md
[ffi-rs](https://github.com/zhangyuang/node-ffi-rs) is a high performance module written in Rust and N-API that provides FFI (Foreign Function Interface) features for Node.js. It allows developers to call functions written in other languages such as C++, C, and Rust directly from JavaScript without writing any C++ code.
This module aims to provide similar functionality to the node-ffi module, but with a completely rewritten underlying codebase. The node-ffi module has been unmaintained for several years and is no longer usable, which is why ffi-rs was developed.
=> docs: add node-ffi-rs

README.md
The "arp-scan-rs" project is a minimalistic ARP scan tool written in Rust for fast local network scans - inspired by the [arp-scan project](https://github.com/royhills/arp-scan) written in C.
=> Add the arp-scan-rs project

README.md
Thanks for the awesome listing! I added my project `async-dropper` which is for people who want an `AsyncDrop` -- it has two implementations (one derive macro based, the other a simple wrapper object)
=> feat: add async-dropper to asynchronous libs

README.md
Hi!
This PR adds ParadeDB and its two main libraries (search and analytics), which can also be used independently of ParadeDB itself. Everything is written in Rust via the `pgrx` framework. Thank you for maintaining this repository and for including us!
=> Add ParadeDB and its libraries

.github/workflows/lint.yml, .github/workflows/rust.yml
Fixes all bar the always-upload-cache. I've filed a bug there (https://github.com/pat-s/always-upload-cache/issues/3) to fix it, or at some point `actions/cache` might be usable for this now, but that has it's own issue (https://github.com/actions/cache/issues/1315)
=> Actions upgrade for node 16 issues

README.md
Thank you for maintaining awesome repository!
I added [typos](https://github.com/crate-ci/typos) [[typos-cli](https://crates.io/crates/typos-cli)] to the list, which helps reduce the time developers spend checking for typos.
Please take a look!
=> Add crate-ci/typos

README.md
This extension is officially deprecated and replaced by [rust-analyzer](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer).
=> Remove deprecated vsc extension from README.md

README.md
zstd-rs is a rust binding for the zstd compression library.
=> add zstd-rs

README.md
Raspirus is a small malware scanner that focuses on being easy to use and as efficient as possible, making it able to work even on Raspberry Pis
Requirements:
=> Add Raspirus

README.md, src/main.rs
If you had a link of the form `[Github link a] blah, blah [Github link b]`, in general `github link A` is the real project, and `github link B` is the upstream project A is bindings to or similar. Previously, the CI would overwrite the star count from A with B, and so A could get in even if it didn't have enough stars.
This PR fixes that.
=> Remove links with more popular upstreams but less popular downstreams

README.md
Adding in Pinepods. A Rust based Podcast management solution that's self hosted and all contained on your own server with a Yew wasm frontend and Tauri based clients.
=> Added Pinepods

README.md
A PR was recently merged to add ParadeDB and its Rust-based Postgres extensions, pg_search and pg_analytics, to this awesome list. This PR adds our latest and final extension, pg_lakehouse.
=> Add pg_lakehouse

README.md
This PR adds three new crates, 
1. [Computation] [`faer`](https://github.com/sarah-ek/faer-rs): 1.6K stars, 59K downloads
2. [Databases] [`lancedb`](https://github.com/lancedb/lancedb): 3K stars, 15K downloads
3. [Artificial Intelligence] [`rust-bert`](https://github.com/guillaume-be/rust-bert): 2.4K stars, 80K downloads
=> add rust-bert, lancedb and faer crates in README.md

README.md
tracexec is a tracer for execve{,at} and pre-exec behavior, and launcher for debuggers. 
In general, it's useful for debugging build systems, understanding what shell scripts actually do, figuring out what programs does a proprietary software run and attaching debuggers to complex multi-process scripts/applications.
=> Add tracexec

README.md
Crates.IO README for cargo-deps says the project is no longer worked on and that users should consider using either cargo-depgraph or cargo-tree. Since cargo-tree is included in cargo, I added cargo-depgraph.
=> Added cargo-depgraph, replacement for cargo-deps

README.md
Found this when I ran the build locally without the results yaml files. It failed because archived repos are treated as zero stars.
The https://github.com/serayuzgur/crates repo has been archived and is now pointing users to https://github.com/filllabs/dependi (a typescript project so no replacement for this list)
=> Removed crates - repo archived

README.md, src/main.rs
Replaced "Better TOML" VSCode extension (deprecated) with "Even Better TOML" (currently in preview).
=> Replaced "Better TOML" (deprecated) with "Even Better TOML"

README.md
`json-rust` is now regarded as abandoned.
https://rustsec.org/advisories/RUSTSEC-2022-0081.html
`jzon-rust` is a community-driven fork of `json-rust`.
=> Replace json-rust with jzon-rust

README.md
Datafusion is mainly used as a library to build data systems, instead of an application.
=> Move datafusion to data processing and update desc

README.md
Add a library called 'dicom-rs', which is a Rust-based implementation of the DICOM standard.
=> Add a library called 'dicom-rs'

README.md
I was looking for something like this and the options listed are not really helpful since:
- scirust is unmaintained since 7 year. (Should we just scratch it at this point?)
- russell isn't written in pure rust which makes it less cross platform than `Peroxide` and I need that
- `peroxide` is actively maintained
=> add `Peroxide` numeric library

README.md
Rebos is a tool that aims at mimicking what NixOS does (repeatability), for any Linux distribution.
It achieves this by using a generation system and calculating diffs between generations, thus, it can also remove old entries (packages, services, groups, etc...) from the system.
Rebos works on any Linux distro. In order to remove packages and services and stuff, you create managers, and Rebos executes the commands specified with the managers and the arguments interpolated in.
=> added rebos - A declarative way to automate package management on any linux distro

README.md
Along with my submission, I'm proposing a new sub-category under Applications: `MLOps`. Rust is increasingly being used for high-performance MLOps tooling, so it'd be great to showcase them!
I'm including an open-source project I co-authored: https://github.com/tensorzero/tensorzero
Let me know if this is not a good fit, and I'd be happy to move it elsewhere. Thanks!
=> Add "MLOps" sub-category and include TensorZero project

README.md
I'm proposing adding [brush](https://github.com/reubeno/brush) to system tools list, now that its download count on [crates.io](https://crates.io/crates/brush-shell) has gone above 3,000:
[![Crates.io](https://img.shields.io/crates/d/brush-shell?style=flat-square)](https://crates.io/crates/brush-shell)
I'm the primary maintainer of the project and happy to answer any questions about it. This is also my first proposed addition to this list and am happy to take any feedback you have on this change. Thanks in advance for your consideration!
=> add brush shell

README.md
First of all, thanks for such a great project. I am a beginner trying to make an open source contribution, and I found this project while looking for a suitable github repo.
Then, by chance, I looked into a project [`notty`](https://github.com/withoutboats/notty). The last update is 7 years ago and the author said [the project is dead](https://github.com/withoutboats/notty/issues/67#issuecomment-354379883).
=> Remove notty

README.md
Add Rust Skill Tree to Resource/Learning section
I work at LabEx, a unique learning platform that has delivered thousands of hands-on labs over the past 7 years. Our Rust Skill Tree currently offers 30 foundational skills and 200+ hands-on labs, making it perfect for beginners to learn step by step. We've now added the Rust Skill Tree to our learning section.
This repo is a great resource for Rust users. Please let me know if any changes are needed.
=> Add Rust Skill Tree to Resource/Learning section

README.md
A library to retrieve system, kernel, and process metrics from the pseudo-filesystems /proc and /sys
=> add procsys

README.md
Hi, Tom
I’m submitting a contribution with three articles that provide a concise history of Rust. These articles are valuable resources for Rustaceans interested in learning about the evolution of Rust. Each article has received over 100 claps on Medium, reflecting positive reader engagement. Importantly, all provided links are accessible for free, and for the paywalled article, I have included a friend link to ensure free access.
Thank you for considering this addition! I believe it will be a helpful resource for the Rust community.
Best regards,
Bin Wu
=> Add 'A Brief History of Rust. Part 1, 2 and 3' under Resources

README.md
I'm using this library to develop reverse engineering and security tools. I think it would be a great addition to the list, but I couldn't find a suitable category, so I added one. I hope it's ok!
=> Add "binarly-io/idalib" under the new "reverse engineering" category

README.md
adds [Hiqlite](https://github.com/sebadob/hiqlite) / https://crates.io/crates/hiqlite
=> Add `hiqlite`

README.md
> Discontinued. Use [Redlib](https://github.com/redlib-org/redlib) instead.
=> Replace discontinued libreddit with its successor Redlib

README.md
Adding gdnext (godot rust bindings for Godot 4+), and updating gdnative to explain it's for Godot 3+.
=> Adding gdnext (godot rust bindings for godot 4+)

README.md
https://github.com/adamperkowski/highlightos
=> Add HighlightOS

README.md
Hello, 
This PR adds similar "Finance" application category as there is for libraries.  
And secondly, it adds Tackler-NG to that Finance  application category.  Tackler-NG is fast, 
reliable bookkeeping engine with native GIT SCM support for plain text accounting.
Github: https://github.com/e257-fi/tackler-ng
Crates.io: https://crates.io/crates/tackler
Sorry to stepping ahead if the  finance application category doesn't make sense, then please just reject this PR and I will make a new one without it. In that case, would the top level Application list be ok for tackler?
=> Add "Finance" app category and Tackler-NG accounting application

README.md
repo: https://github.com/alexpasmantier/television
=> add `television` to `Applications/Utilities`

README.md
Ape Data Transfer Suite. Provides ultra-fast data replication between MySQL, PostgreSQL, Redis, MongoDB, Kafka and ClickHouse, and more.
=> Add ape-dts

README.md
- Mega - monorepo & monolithic codebase management system
- Dagrs - A high-performance asynchronous task programming framework, which follows the concept of Flow-based Programming
=> Add mega and dagrs

README.md
Moved haruspex and rhabdomancer under "security tools" and removed the "vulnerability research" category.
=> Moved haruspex and rhabdomancer under "security tools"

README.md
The crates.io link still pointed to the old crate.
=> Update hickory-dns link

README.md
Bringing the names of projects to a common form (so that they are not highlighted in capital letters)
=> Fix naming project

README.md
Adding crate `differential-equations` to the Computing -> Science section. Significantly more feature-rich and has an idiomatic API than previous Rust implementations. Additionally, benchmarking is faster than the gold standard Fortran implementations.
=> add differential-equations

README.md
This PR adds a recommendation for the repository [clash-verge-rev](https://github.com/clash-verge-rev/clash-verge-rev) to the list. Clash Verge Rev is a cross-platform Clash GUI based on Tauri, written in Rust, providing a modern, user-friendly interface for managing network proxies. It is actively maintained and widely used in the community.
=> add clash-verge-rev to applications list in README

README.md
Adds mocktail, a HTTP & gRPC server mocking crate, to the `Developer Tools > Testing > Mocking and Test Data` section.
=> Add mocktail

README.md, src/main.rs
RepoFlow is a modern repository platform that can host Rust crate registries and proxy crates.io. It also supports formats like Docker, PyPI, Maven, npm, and RubyGems. Available as a cloud or self-hosted solution.
This entry was added alphabetically under the Registries section and meets the contribution guidelines for popularity and maintenance.
Public documentation: https://docs.repoflow.io
Official website: https://www.repoflow.io
=> Add RepoFlow to Registries section

README.md
BAML is a new programming language to interact with LLMs whose compiler is written in Rust.
https://github.com/BoundaryML/baml
=> Add BAML as a new link under tooling in the AI section

README.md
This PR adds three high-performance Rust libraries to the Awesome Rust list:
- **datalogic-rs** — High-performance, type-safe JSONLogic evaluation engine in Rust, ideal for business rules and dynamic filtering.   Repo: https://github.com/GoPlasmatic/datalogic-rs
- **dataflow-rs** — Event-driven, code-defined workflow orchestration engine in Rust for building high-performance data pipelines.   Repo: https://github.com/GoPlasmatic/dataflow-rs
- **datafake-rs** — High-performance JSON mock-data generator in Rust for fast and flexible test-data generation.   Repo: https://github.com/GoPlasmatic/datafake-rs
These libraries are designed with performance and developer productivity in mind, and they complement the Rust ecosystem in expression evaluation, workflow orchestration, and test-data …
=> Add datalogic-rs, dataflow-rs, and datafake-rs to Awesome Rust

README.md
Added https://github.com/topheman/webassembly-component-model-experiments to System tools section, with link to the published crate: https://crates.io/crates/pluginlab
=> Added topheman/webassembly-component-model-experiments to System tools section

README.md
This PR adds [rkik](https://github.com/aguacero7/rkik) to the **Applications** section.
`rkik` is a command-line tool written in Rust for querying or comparing multiple time servers ( for now, only using the ntp protocol).  
It is also available as a library but this is not the main point of the project.
It already has 2k+ downloads on [crates.io](https://crates.io/crates/rkik)
=> Add rkik to Applications section

README.md
**Repo link**: https://github.com/graves/awful_aj
**Crate link**: https://crates.io/crates/awful_aj
**Description**:
Awful Jade (`aj`) is a Rust-based command-line assistant for working with Large Language Models (LLMs). It acts as an LLM Swiss Army knife, letting you ask questions, run interactive conversations, manage context with embeddings, and drive workflows directly from your terminal. With YAML-driven configs and templates, it’s fast, extensible, and entirely user-controlled.
Why I think it’s awesome:
- It **brings LLM workflows into the terminal** in a way that’s structured, efficient, and fun.
- **Ask & Interactive Sessions**: Jump between one-off questions or REPL-style chats with memory.
- **Vector Store Memory**: Uses embeddings + HNSW so the assistant "remembers" context …
=> Add awful_aj OpenAI-compatible CLI tool 
